import { createContext, useState, useContext, useEffect, ReactNode } from 'react';

export type Language = {
  code: string;
  name: string;
  flag: string;
};

// Define our translation object type
export type Translations = {
  [key: string]: string;
};

// Define a type for our translations by language
export type AllTranslations = {
  [languageCode: string]: Translations;
};

// Default translations for the application
const translations: AllTranslations = {
  fr: {
    // Header
    features: "Fonctionnalités",
    modules: "Modules",
    ai: "Intelligence Artificielle",
    contact: "Contact",
    freeTrial: "Essai Gratuit",
    dashboard: "Tableau de bord",
    signOut: "Se déconnecter",
    connectPharmacy: "Connecter pharmacie",
    disconnectPharmacy: "Déconnecter pharmacie",
    pharmacy: "Pharmacie",
    // Hero
    heroTitle: "Solution complète de gestion pharmaceutique",
    heroTagline: "La solution complète pour votre pharmacie",
    heroTransformTitle1: "Transformez la gestion",
    heroTransformTitle2: "de votre officine",
    heroDescription: "PharmaSoft est une application complète de gestion d'officine pharmaceutique disponible en version web et mobile, conçue pour simplifier tous vos processus.",
    connectYourPharmacy: "Connecter votre Pharmacie",
    loading: "Chargement...",
    seeDemo: "Voir la Démo",
    pharmaciesUsing: "pharmacies utilisent déjà PharmaSoft",
    stocks: "Stocks",
    optimal: "Optimal",
    attention: "Attention",
    critical: "Critique",
    products: "produits",
    availability: "disponibilité",
    sales: "Ventes",
    activeSession: "Session active",
    // Features
    featuresTitle: "Toutes les fonctionnalités dans une seule solution",
    featuresSubtitle: "Pharmasoft révolutionne la gestion de votre pharmacie avec un ensemble complet d'outils intégrés et innovants.",
    salesManagement: "Gestion des ventes",
    salesDesc: "Point de vente tactile, gestion des ordonnances, remises et promotions automatisées.",
    stockManagement: "Gestion des stocks",
    stockDesc: "Inventaire en temps réel, alertes de seuil, commandes automatisées, suivi des péremptions.",
    clientManagement: "Gestion des clients",
    clientDesc: "Base de données clients, historique d'achats, programme de fidélité, segmentation.",
    cashManagement: "Gestion de caisse",
    cashDesc: "Multi-caisses, suivi des encaissements, clôtures journalières, rapports détaillés.",
    analytics: "Analyses & Rapports",
    analyticsDesc: "Tableaux de bord analytiques, rapports personnalisés, prévisions et tendances.",
    security: "Sécurité avancée",
    securityDesc: "Authentification multi-facteurs, gestion fine des droits d'accès, chiffrement des données.",
    webMobile: "Web & Mobile",
    webMobileDesc: "Application web responsive et applications mobiles natives (iOS et Android).",
    multilingual: "Multilingue",
    multilingualDesc: "Application disponible en 4 langues : Français, Anglais, Espagnol et Lingala.",
    voiceCommands: "Commandes vocales",
    voiceDesc: "Contrôlez l'application par la voix, dictée vocale et reconnaissance des médicaments.",
    // Footer
    footerDescription: "Une application complète de gestion d'officine pharmaceutique disponible en version web et mobile.",
    quickLinks: "Liens rapides",
    contactUs: "Contactez-nous",
    newsletter: "Inscription à la newsletter",
    newsletterDesc: "Recevez les dernières mises à jour et offres spéciales.",
    email: "Votre email",
    subscribe: "S'abonner",
    pricing: "Tarifs",
    blog: "Blog",
    termsOfUse: "Conditions d'utilisation",
    privacyPolicy: "Politique de confidentialité",
    legalNotice: "Mentions légales",
    allRightsReserved: "Tous droits réservés.",
    // Dashboard - Main
    dashboardTitle: "Tableau de Bord",
    refresh: "Actualiser",
    // Dashboard - Sales Metrics
    dailySalesTitle: "Ventes du Jour",
    monthlySalesTitle: "CA Mensuel",
    dailyTransactions: "Transactions Jour",
    averageBasket: "Panier Moyen",
    vsYesterday: "vs hier",
    thisMonth: "Ce mois",
    salesCompleted: "Ventes réalisées",
    perTransaction: "Par transaction",
    // Dashboard - Stock Metrics
    totalStockValue: "Valeur Stock Total",
    availableProducts: "Produits Disponibles",
    lowStockAlerts: "Alertes Stock Faible",
    outOfStock: "Produits en Rupture",
    totalInventory: "Inventaire total",
    sufficientStock: "En stock suffisant",
    toReorder: "À réapprovisionner",
    stockDepleted: "Stock épuisé",
    // Dashboard - Quick Actions
    quickActions: "Actions Rapides",
    newSale: "Nouvelle Vente",
    openRegister: "Ouvrir Caisse",
    payment: "Paiement",
    inventory: "Inventaire",
    reports: "Rapports",
    pos: "Point de vente",
    cashManagementAction: "Gestion caisses",
    collections: "Encaissements",
    stockManagementAction: "Gestion stock",
    // Dashboard - Critical Alerts
    criticalAlerts: "Alertes Critiques",
    noCriticalAlerts: "Aucune alerte critique",
    units: "unités",
    unknownDate: "Date inconnue",
    expiresOn: "Expire le",
    // Dashboard - Recent Activities
    recentActivities: "Activités Récentes",
    noRecentActivities: "Aucune activité récente",
    newSaleActivity: "Nouvelle vente",
    saleModified: "Vente modifiée",
    saleDeleted: "Vente supprimée",
    supplierReception: "Réception fournisseur",
    receptionUpdated: "Réception mise à jour",
    receptionDeleted: "Réception supprimée",
    inventoryCreated: "Inventaire créé",
    inventoryUpdated: "Inventaire mis à jour",
    inventoryDeleted: "Inventaire supprimé",
    registerOpened: "Session caisse ouverte",
    registerUpdated: "Session caisse mise à jour",
    registerDeleted: "Session caisse supprimée",
    // Dashboard - Top Products
    topProducts: "Produits les Plus Vendus",
    noTopProducts: "Aucun produit vendu",
    soldUnits: "vendus",
    // Dashboard - Active Sessions
    activeSessions: "Sessions Caisse Actives",
    noActiveSessions: "Aucune session active",
    openingBalance: "Fond de caisse",
    currentAmount: "Montant actuel",
    salesCount: "Ventes",
    // Dashboard - Credit & Promotions
    clientCredit: "Crédit Clients",
    totalOngoing: "Total en cours",
    activeAccounts: "Comptes actifs",
    paymentDelays: "Retards de paiement",
    utilizationRate: "Taux d'utilisation",
    promotions: "Promotions",
    active: "Actives",
    usages: "Utilisations",
    savingsToday: "Économies aujourd'hui",
    // Sidebar Menu
    mainMenu: "Principal",
    administration: "Administration",
    stock: "Stock",
    salesMenu: "Ventes",
    accounting: "Comptabilité",
    reportsMenu: "Rapports",
    aiAssistant: "Assistant IA",
    chatNetwork: "Chat-PharmaSoft",
    settings: "Paramètres",
    testsMenu: "Tests & Développement",
    testSuites: "Suites de Tests",
    signOutLabel: "Déconnexion",
    logoutSuccess: "Vous avez été déconnecté avec succès.",
    // General
    dailySales: "Ventes du jour",
    customerServices: "Services clients",
    productsToRenew: "Produits à renouveler",
    last7Days: "Ventes des 7 derniers jours",
    upcomingAppointments: "Prochains rendez-vous",
    help: "Aide",
    logout: "Déconnexion",
    // Help Center
    helpCenter: "Centre d'aide",
    searchHelp: "Rechercher dans l'aide...",
    recentlyViewed: "Récemment consulté",
    helpModules: "Modules",
    quickFAQ: "FAQ Rapide",
    videoTutorials: "Tutoriels Vidéo",
    wasHelpful: "Cet article vous a-t-il aidé ?",
    noResults: "Aucun résultat trouvé",
    searchTip: "Conseil : essayez des mots-clés différents",
    relatedArticles: "Articles liés",
    stepByStep: "Procédure pas-à-pas",
    viewAllTutorials: "Voir tous les tutoriels",
    // Sales module translations
    searchProducts: "Rechercher des produits par nom ou catégorie",
    searchPlaceholder: "Rechercher un médicament...",
    noProductsFound: "Aucun produit trouvé",
    inStock: "En stock",
    add: "Ajouter",
    cart: "Panier",
    emptyCart: "Votre panier est vide",
    itemsInCart: "articles dans le panier",
    itemInCart: "article dans le panier",
    cartEmpty: "Ajoutez des produits à votre panier",
    total: "Total",
    checkout: "Finaliser la vente",
    // ====================== ADMINISTRATION MODULE ======================
    // Personnel Module
    personnelManagement: "Gestion du Personnel",
    personnelDescription: "Gestion des employés, horaires, congés et formations (hors gestion des utilisateurs système)",
    noPermission: "Vous n'avez pas les permissions nécessaires pour accéder à ce module.",
    employees: "Employés",
    schedules: "Horaires",
    leaves: "Congés",
    trainings: "Formations",
    // Employee Management
    employeeManagement: "Gestion des Employés",
    employeeManagementDesc: "Gérez les informations personnelles et professionnelles de vos employés",
    newEmployee: "Nouvel Employé",
    editEmployee: "Modifier l'employé",
    createEmployee: "Créer un nouvel employé",
    searchEmployee: "Rechercher un employé...",
    totalEmployees: "Total employés",
    employeeCreated: "Employé créé avec succès",
    employeeUpdated: "Employé modifié avec succès",
    employeeDeleted: "Employé supprimé avec succès",
    noEmployeeFound: "Aucun employé trouvé pour cette recherche",
    noEmployeeRegistered: "Aucun employé enregistré",
    confirmDeleteEmployee: "Êtes-vous sûr de vouloir supprimer cet employé ?",
    loadingEmployees: "Chargement des employés...",
    formValidationError: "Erreur lors de la validation du formulaire. Veuillez vérifier tous les champs.",
    // Employee Form Labels
    lastName: "Noms",
    firstName: "Prénoms",
    function: "Fonction",
    selectFunction: "Sélectionner une fonction",
    address: "Adresse",
    addressOptional: "Adresse (optionnel)",
    phone: "Téléphone d'appel",
    whatsapp: "WhatsApp (optionnel)",
    nationalId: "NIU/CNI",
    profession: "Profession (optionnel)",
    birthDate: "Date de naissance",
    hireDate: "Date de recrutement",
    photo: "Photo d'identité",
    baseSalary: "Salaire de base (optionnel)",
    familyStatus: "Situation familiale",
    selectFamilyStatus: "Sélectionner la situation",
    childrenCount: "Nombre d'enfants",
    socialSecurityNumber: "Numéro CNSS (optionnel)",
    contractStatus: "Statut contractuel",
    selectContractStatus: "Sélectionner le statut",
    clientAccountInfo: "Infos Compte Client",
    insurerOptional: "Assureur (optionnel)",
    noInsurer: "Aucun assureur",
    autoDiscountRate: "Taux de remise auto (%)",
    debtLimit: "Limite de dette",
    canTakeVoucher: "Peut prendre des bons",
    agentRate: "Taux agent (%)",
    beneficiaryRate: "Taux ayant droit (%)",
    moderatorTicketRate: "Taux ticket modérateur (%)",
    deposit: "Caution",
    // Contract Types
    cdi: "CDI",
    cdd: "CDD",
    internship: "Stage",
    freelance: "Freelance",
    // Family Statuses
    single: "Célibataire",
    married: "Marié(e)",
    divorced: "Divorcé(e)",
    widowed: "Veuf(ve)",
    // Job Functions
    pharmacistOwner: "Pharmacien Titulaire",
    assistantPharmacist: "Pharmacien Adjoint",
    preparer: "Préparateur",
    technician: "Technicien",
    cashier: "Caissier",
    seller: "Vendeur",
    stockManager: "Gestionnaire de stock",
    accountant: "Comptable",
    secretary: "Secrétaire",
    deliveryPerson: "Livreur",
    intern: "Stagiaire",
    // Employee Filters
    filterByFunction: "Filtrer par fonction",
    filterByStatus: "Filtrer par statut",
    filterByFamilyStatus: "Filtrer par situation familiale",
    minSalary: "Salaire minimum",
    maxSalary: "Salaire maximum",
    clearFilters: "Effacer les filtres",
    filters: "Filtres",
    // Schedule Management
    scheduleManagement: "Gestion des Horaires",
    scheduleManagementDesc: "Planifiez les horaires de travail de vos employés",
    newSchedule: "Nouvel horaire",
    editSchedule: "Modifier l'horaire",
    date: "Date",
    startTime: "Heure de début",
    endTime: "Heure de fin",
    shiftType: "Type de service",
    post: "Poste/Zone",
    scheduleStatus: "Statut",
    notes: "Notes",
    morning: "Matin",
    afternoon: "Après-midi",
    night: "Nuit",
    full: "Journée complète",
    planned: "Planifié",
    confirmed: "Confirmé",
    cancelled: "Annulé",
    scheduleCreated: "Horaire créé avec succès",
    scheduleUpdated: "Horaire modifié avec succès",
    scheduleDeleted: "Horaire supprimé avec succès",
    noScheduleFound: "Aucun horaire trouvé",
    loadingSchedules: "Chargement des horaires...",
    // Leave Management
    leaveManagement: "Gestion des Congés",
    leaveManagementDesc: "Gérez les demandes de congés de vos employés",
    newLeaveRequest: "Nouvelle demande de congé",
    editLeaveRequest: "Modifier la demande",
    leaveType: "Type de congé",
    startDate: "Date de début",
    endDate: "Date de fin",
    reason: "Motif",
    comments: "Commentaires",
    pending: "En attente",
    approved: "Approuvé",
    rejected: "Refusé",
    paidLeave: "Congé payé",
    unpaidLeave: "Congé sans solde",
    sickLeave: "Congé maladie",
    maternityLeave: "Congé maternité",
    paternityLeave: "Congé paternité",
    leaveCreated: "Demande de congé créée avec succès",
    leaveUpdated: "Demande de congé modifiée avec succès",
    leaveDeleted: "Demande de congé supprimée",
    noLeaveFound: "Aucune demande de congé trouvée",
    loadingLeaves: "Chargement des congés...",
    // Training Management
    trainingManagement: "Gestion des Formations",
    trainingManagementDesc: "Organisez les formations pour vos employés",
    newTraining: "Nouvelle formation",
    editTraining: "Modifier la formation",
    trainingName: "Nom de la formation",
    trainingDescription: "Description",
    trainingStartDate: "Date de début",
    trainingEndDate: "Date de fin",
    duration: "Durée",
    location: "Lieu",
    cost: "Coût",
    participants: "Participants",
    addParticipant: "Ajouter un participant",
    removeParticipant: "Retirer",
    selectEmployee: "Sélectionner un employé",
    trainingStatus: "Statut",
    scheduled: "Programmée",
    inProgress: "En cours",
    completed: "Terminée",
    trainingCreated: "Formation créée avec succès",
    trainingUpdated: "Formation modifiée avec succès",
    trainingDeleted: "Formation supprimée",
    noTrainingFound: "Aucune formation trouvée",
    loadingTrainings: "Chargement des formations...",
    // Partner Module
    partnersOverview: "Vue d'ensemble",
    insurers: "Assureurs",
    companies: "Sociétés",
    conventioned: "Conventionnés",
    suppliers: "Fournisseurs",
    laboratories: "Laboratoires",
    insuranceCompanies: "Compagnies d'assurance",
    partnerCompanies: "Entreprises partenaires",
    conventionedEstablishments: "Établissements conventionnés",
    activeSuppliers: "Fournisseurs actifs",
    pharmaLabs: "Laboratoires pharmaceutiques",
    recentPartners: "Partenaires Récents",
    addedAgo: "Ajouté il y a",
    days: "jours",
    week: "semaine",
    weeks: "semaines",
    manageInsurers: "Gérer les Assureurs",
    manageSuppliers: "Gérer les Fournisseurs",
    manageLabs: "Gérer les Laboratoires",
    // Insurance Manager
    insurerManagement: "Gestion des Assureurs",
    newInsurer: "Nouvel Assureur",
    editInsurer: "Modifier l'assureur",
    searchInsurer: "Rechercher un assureur...",
    insurerName: "Nom de l'assureur",
    niu: "NIU",
    insurerAdded: "Assureur ajouté avec succès",
    insurerModified: "Assureur modifié avec succès",
    insurerDeleted: "Assureur supprimé",
    noInsurerFound: "Aucun assureur trouvé",
    contacts: "Contacts",
    notProvided: "Non renseignée",
    actions: "Actions",
    // Supplier Manager
    supplierManagement: "Gestion des Fournisseurs",
    newSupplier: "Nouveau Fournisseur",
    editSupplier: "Modifier le fournisseur",
    searchSupplier: "Rechercher un fournisseur...",
    supplierName: "Nom du fournisseur",
    supplierAdded: "Fournisseur ajouté avec succès",
    supplierModified: "Fournisseur modifié avec succès",
    supplierDeleted: "Fournisseur supprimé",
    noSupplierFound: "Aucun fournisseur trouvé",
    // Laboratory Manager
    laboratoryManagement: "Gestion des Laboratoires",
    newLaboratory: "Nouveau Laboratoire",
    editLaboratory: "Modifier le laboratoire",
    searchLaboratory: "Rechercher un laboratoire...",
    laboratoryName: "Nom du laboratoire",
    laboratoryAdded: "Laboratoire ajouté avec succès",
    laboratoryModified: "Laboratoire modifié avec succès",
    laboratoryDeleted: "Laboratoire supprimé",
    noLaboratoryFound: "Aucun laboratoire trouvé",
    // Company Manager
    companyManagement: "Gestion des Sociétés",
    newCompany: "Nouvelle Société",
    editCompany: "Modifier la société",
    searchCompany: "Rechercher une société...",
    companyName: "Nom de la société",
    companyAdded: "Société ajoutée avec succès",
    companyModified: "Société modifiée avec succès",
    companyDeleted: "Société supprimée",
    noCompanyFound: "Aucune société trouvée",
    // Conventioned Manager
    conventionedManagement: "Gestion des Conventionnés",
    newConventioned: "Nouveau Conventionné",
    editConventioned: "Modifier le conventionné",
    searchConventioned: "Rechercher un conventionné...",
    conventionedName: "Nom du conventionné",
    conventionedAdded: "Conventionné ajouté avec succès",
    conventionedModified: "Conventionné modifié avec succès",
    conventionedDeleted: "Conventionné supprimé",
    noConventionedFound: "Aucun conventionné trouvé",
    // Referentiel Module
    referentielOverview: "Vue d'ensemble",
    catalog: "Catalogue",
    forms: "Formes",
    families: "Familles",
    shelves: "Rayons",
    categories: "Catégories",
    dci: "DCI",
    therapeuticClasses: "Classes thérapeutiques",
    regulations: "Réglementations",
    referencedProducts: "Produits référencés",
    productFamilies: "Familles de produits",
    galenicForms: "Formes galéniques",
    organizationalShelves: "Rayons organisationnels",
    pricingCategories: "Catégories tarifaires",
    activeIngredients: "Principes actifs",
    regulatoryStatuses: "Statuts réglementaires",
    recentProducts: "Produits Récents",
    addedOn: "Ajouté",
    product: "Produit",
    noRecentProduct: "Aucun produit récent",
    manageCatalog: "Gérer le Catalogue",
    manageFamilies: "Gérer les Familles",
    manageCategories: "Gérer les Catégories",
    // Family Manager
    familyManagementTitle: "Familles de Produits",
    newFamily: "Ajouter",
    editFamily: "Modifier la famille",
    addFamily: "Ajouter une famille",
    searchFamily: "Rechercher une famille...",
    familyLabel: "Libellé de la famille",
    description: "Description",
    familyAdded: "Famille ajoutée avec succès",
    familyModified: "Famille modifiée avec succès",
    familyDeleted: "Famille supprimée avec succès",
    noFamilyFound: "Aucune famille trouvée",
    label: "Libellé",
    // Formes Manager
    formesManagementTitle: "Formes Galéniques",
    newForm: "Ajouter",
    editForm: "Modifier la forme",
    searchForm: "Rechercher une forme...",
    formLabel: "Libellé de la forme",
    formAdded: "Forme ajoutée avec succès",
    formModified: "Forme modifiée avec succès",
    formDeleted: "Forme supprimée avec succès",
    noFormFound: "Aucune forme trouvée",
    // Rayon Manager
    rayonManagementTitle: "Rayons de Produits",
    newRayon: "Ajouter un Rayon",
    editRayon: "Modifier le rayon",
    searchRayon: "Rechercher un rayon...",
    rayonLabel: "Libellé du rayon",
    rayonAdded: "Rayon ajouté avec succès",
    rayonModified: "Rayon modifié avec succès",
    rayonDeleted: "Rayon supprimé avec succès",
    noRayonFound: "Aucun rayon trouvé",
    // DCI Manager
    dciManagementTitle: "Dénominations Communes Internationales",
    newDci: "Ajouter",
    editDci: "Modifier le DCI",
    searchDci: "Rechercher un DCI...",
    dciLabel: "Libellé du DCI",
    dciAdded: "DCI ajouté avec succès",
    dciModified: "DCI modifié avec succès",
    dciDeleted: "DCI supprimé avec succès",
    noDciFound: "Aucun DCI trouvé",
    // Therapeutic Class Manager
    therapeuticClassManagementTitle: "Classes Thérapeutiques",
    newTherapeuticClass: "Ajouter",
    editTherapeuticClass: "Modifier la classe",
    searchTherapeuticClass: "Rechercher une classe...",
    therapeuticClassLabel: "Libellé de la classe",
    therapeuticClassAdded: "Classe ajoutée avec succès",
    therapeuticClassModified: "Classe modifiée avec succès",
    therapeuticClassDeleted: "Classe supprimée avec succès",
    noTherapeuticClassFound: "Aucune classe trouvée",
    // Pricing Categories
    pricingCategoriesTitle: "Catégories Tarifaires",
    newCategory: "Ajouter",
    editCategory: "Modifier la catégorie",
    searchCategory: "Rechercher une catégorie...",
    categoryLabel: "Libellé de la catégorie",
    categoryAdded: "Catégorie ajoutée avec succès",
    categoryModified: "Catégorie modifiée avec succès",
    categoryDeleted: "Catégorie supprimée avec succès",
    noCategoryFound: "Aucune catégorie trouvée",
    // Regulation Tracker
    regulationTrackerTitle: "Réglementations",
    newRegulation: "Ajouter",
    editRegulation: "Modifier la réglementation",
    searchRegulation: "Rechercher une réglementation...",
    regulationLabel: "Libellé de la réglementation",
    regulationAdded: "Réglementation ajoutée avec succès",
    regulationModified: "Réglementation modifiée avec succès",
    regulationDeleted: "Réglementation supprimée avec succès",
    noRegulationFound: "Aucune réglementation trouvée",
    // Product Catalog
    productCatalogTitle: "Catalogue de Produits",
    newProduct: "Nouveau Produit",
    editProduct: "Modifier le produit",
    searchProduct: "Rechercher un produit...",
    productName: "Nom du produit",
    productAdded: "Produit ajouté avec succès",
    productModified: "Produit modifié avec succès",
    productDeleted: "Produit supprimé avec succès",
    noProductFound: "Aucun produit trouvé",
    // Client Module
    clientsOverview: "Analytics",
    clients: "Clients",
    clientModuleTitle: "Gestion des Clients",
    clientModuleDesc: "Consultez et gérez tous vos clients",
    clientCreation: "Création de clients",
    clientCreationInfo: "Les comptes clients sont créés automatiquement depuis les modules",
    personnelModule: "Personnel",
    companyModule: "Entreprise",
    conventionedModule: "Conventionné",
    searchClient: "Rechercher un client...",
    totalClients: "Total clients",
    noClientFound: "Aucun client trouvé pour cette recherche",
    noClientRegistered: "Aucun client enregistré",
    loadingClients: "Chargement des clients...",
    discountRate: "Taux de remise",
    clientType: "Type de client",
    confirmDeleteClient: "Êtes-vous sûr de vouloir supprimer ce client ?",
    clientUpdated: "Client modifié avec succès",
    clientDeleted: "Client supprimé avec succès",
    ordinary: "Ordinaire",
    // Common Actions
    cancel: "Annuler",
    save: "Enregistrer",
    create: "Créer",
    modify: "Modifier",
    delete: "Supprimer",
    edit: "Modifier",
    view: "Voir",
    close: "Fermer",
    confirm: "Confirmer",
    search: "Rechercher",
    filter: "Filtrer",
    export: "Exporter",
    import: "Importer",
    back: "Retour",
    next: "Suivant",
    previous: "Précédent",
    submit: "Soumettre",
    reset: "Réinitialiser",
    processing: "En cours...",
    errorLoading: "Erreur lors du chargement des données",
    requiredField: "Ce champ est obligatoire",
    // Table Headers
    name: "Nom",
    status: "Statut",
    createdAt: "Créé le",
    updatedAt: "Mis à jour le",
  },
  en: {
    // Header
    features: "Features",
    modules: "Modules",
    ai: "Artificial Intelligence",
    contact: "Contact",
    freeTrial: "Free Trial",
    dashboard: "Dashboard",
    signOut: "Sign Out",
    connectPharmacy: "Connect pharmacy",
    disconnectPharmacy: "Disconnect pharmacy",
    pharmacy: "Pharmacy",
    // Hero
    heroTitle: "Complete Pharmaceutical Management Solution",
    heroTagline: "The complete solution for your pharmacy",
    heroTransformTitle1: "Transform the management",
    heroTransformTitle2: "of your pharmacy",
    heroDescription: "PharmaSoft is a complete pharmacy management application available in web and mobile versions, designed to simplify all your processes.",
    connectYourPharmacy: "Connect your Pharmacy",
    loading: "Loading...",
    seeDemo: "See Demo",
    pharmaciesUsing: "pharmacies already use PharmaSoft",
    stocks: "Stocks",
    optimal: "Optimal",
    attention: "Warning",
    critical: "Critical",
    products: "products",
    availability: "availability",
    sales: "Sales",
    activeSession: "Active session",
    // Features
    featuresTitle: "All features in one solution",
    featuresSubtitle: "Pharmasoft revolutionizes your pharmacy management with a complete set of integrated and innovative tools.",
    salesManagement: "Sales Management",
    salesDesc: "Touch POS, prescription management, automated discounts and promotions.",
    stockManagement: "Inventory Management",
    stockDesc: "Real-time inventory, threshold alerts, automated orders, expiration tracking.",
    clientManagement: "Customer Management",
    clientDesc: "Customer database, purchase history, loyalty program, segmentation.",
    cashManagement: "Cash Management",
    cashDesc: "Multi-registers, payment tracking, daily closings, detailed reports.",
    analytics: "Analytics & Reports",
    analyticsDesc: "Analytical dashboards, custom reports, forecasts and trends.",
    security: "Advanced Security",
    securityDesc: "Multi-factor authentication, fine access rights management, data encryption.",
    webMobile: "Web & Mobile",
    webMobileDesc: "Responsive web application and native mobile applications (iOS and Android).",
    multilingual: "Multilingual",
    multilingualDesc: "Application available in 4 languages: French, English, Spanish and Lingala.",
    voiceCommands: "Voice Commands",
    voiceDesc: "Control the application by voice, voice dictation and medication recognition.",
    // Footer
    footerDescription: "A complete pharmacy management application available in web and mobile versions.",
    quickLinks: "Quick Links",
    contactUs: "Contact Us",
    newsletter: "Newsletter Subscription",
    newsletterDesc: "Receive the latest updates and special offers.",
    email: "Your email",
    subscribe: "Subscribe",
    pricing: "Pricing",
    blog: "Blog",
    termsOfUse: "Terms of Use",
    privacyPolicy: "Privacy Policy",
    legalNotice: "Legal Notice",
    allRightsReserved: "All rights reserved.",
    // Dashboard - Main
    dashboardTitle: "Dashboard",
    refresh: "Refresh",
    // Dashboard - Sales Metrics
    dailySalesTitle: "Daily Sales",
    monthlySalesTitle: "Monthly Revenue",
    dailyTransactions: "Daily Transactions",
    averageBasket: "Average Basket",
    vsYesterday: "vs yesterday",
    thisMonth: "This month",
    salesCompleted: "Sales completed",
    perTransaction: "Per transaction",
    // Dashboard - Stock Metrics
    totalStockValue: "Total Stock Value",
    availableProducts: "Available Products",
    lowStockAlerts: "Low Stock Alerts",
    outOfStock: "Out of Stock",
    totalInventory: "Total inventory",
    sufficientStock: "Sufficient stock",
    toReorder: "To reorder",
    stockDepleted: "Stock depleted",
    // Dashboard - Quick Actions
    quickActions: "Quick Actions",
    newSale: "New Sale",
    openRegister: "Open Register",
    payment: "Payment",
    inventory: "Inventory",
    reports: "Reports",
    pos: "Point of Sale",
    cashManagementAction: "Cash Management",
    collections: "Collections",
    stockManagementAction: "Stock Management",
    // Dashboard - Critical Alerts
    criticalAlerts: "Critical Alerts",
    noCriticalAlerts: "No critical alerts",
    units: "units",
    unknownDate: "Unknown date",
    expiresOn: "Expires on",
    // Dashboard - Recent Activities
    recentActivities: "Recent Activities",
    noRecentActivities: "No recent activities",
    newSaleActivity: "New sale",
    saleModified: "Sale modified",
    saleDeleted: "Sale deleted",
    supplierReception: "Supplier reception",
    receptionUpdated: "Reception updated",
    receptionDeleted: "Reception deleted",
    inventoryCreated: "Inventory created",
    inventoryUpdated: "Inventory updated",
    inventoryDeleted: "Inventory deleted",
    registerOpened: "Register session opened",
    registerUpdated: "Register session updated",
    registerDeleted: "Register session deleted",
    // Dashboard - Top Products
    topProducts: "Top Selling Products",
    noTopProducts: "No products sold",
    soldUnits: "sold",
    // Dashboard - Active Sessions
    activeSessions: "Active Register Sessions",
    noActiveSessions: "No active sessions",
    openingBalance: "Opening balance",
    currentAmount: "Current amount",
    salesCount: "Sales",
    // Dashboard - Credit & Promotions
    clientCredit: "Client Credit",
    totalOngoing: "Total ongoing",
    activeAccounts: "Active accounts",
    paymentDelays: "Payment delays",
    utilizationRate: "Utilization rate",
    promotions: "Promotions",
    active: "Active",
    usages: "Usages",
    savingsToday: "Savings today",
    // Sidebar Menu
    mainMenu: "Main",
    administration: "Administration",
    stock: "Stock",
    salesMenu: "Sales",
    accounting: "Accounting",
    reportsMenu: "Reports",
    aiAssistant: "AI Assistant",
    chatNetwork: "Chat-PharmaSoft",
    settings: "Settings",
    testsMenu: "Tests & Development",
    testSuites: "Test Suites",
    signOutLabel: "Sign Out",
    logoutSuccess: "You have been successfully signed out.",
    // General
    dailySales: "Daily Sales",
    customerServices: "Customer Services",
    productsToRenew: "Products to Renew",
    last7Days: "Sales for the last 7 days",
    upcomingAppointments: "Upcoming Appointments",
    help: "Help",
    logout: "Logout",
    // Help Center
    helpCenter: "Help Center",
    searchHelp: "Search help...",
    recentlyViewed: "Recently Viewed",
    helpModules: "Modules",
    quickFAQ: "Quick FAQ",
    videoTutorials: "Video Tutorials",
    wasHelpful: "Was this article helpful?",
    noResults: "No results found",
    searchTip: "Tip: try different keywords",
    relatedArticles: "Related Articles",
    stepByStep: "Step by Step",
    viewAllTutorials: "View all tutorials",
    // Sales module translations
    searchProducts: "Search products by name or category",
    searchPlaceholder: "Search for a medication...",
    noProductsFound: "No products found",
    inStock: "In stock",
    add: "Add",
    cart: "Cart",
    emptyCart: "Your cart is empty",
    itemsInCart: "items in cart",
    itemInCart: "item in cart",
    cartEmpty: "Add products to your cart",
    total: "Total",
    checkout: "Checkout",
    // ====================== ADMINISTRATION MODULE ======================
    // Personnel Module
    personnelManagement: "Personnel Management",
    personnelDescription: "Manage employees, schedules, leave and training (excluding system user management)",
    noPermission: "You do not have the necessary permissions to access this module.",
    employees: "Employees",
    schedules: "Schedules",
    leaves: "Leave",
    trainings: "Training",
    // Employee Management
    employeeManagement: "Employee Management",
    employeeManagementDesc: "Manage the personal and professional information of your employees",
    newEmployee: "New Employee",
    editEmployee: "Edit employee",
    createEmployee: "Create a new employee",
    searchEmployee: "Search for an employee...",
    totalEmployees: "Total employees",
    employeeCreated: "Employee created successfully",
    employeeUpdated: "Employee updated successfully",
    employeeDeleted: "Employee deleted successfully",
    noEmployeeFound: "No employee found for this search",
    noEmployeeRegistered: "No employees registered",
    confirmDeleteEmployee: "Are you sure you want to delete this employee?",
    loadingEmployees: "Loading employees...",
    formValidationError: "Form validation error. Please check all fields.",
    // Employee Form Labels
    lastName: "Last Name",
    firstName: "First Name",
    function: "Function",
    selectFunction: "Select a function",
    address: "Address",
    addressOptional: "Address (optional)",
    phone: "Phone",
    whatsapp: "WhatsApp (optional)",
    nationalId: "National ID",
    profession: "Profession (optional)",
    birthDate: "Date of birth",
    hireDate: "Hire date",
    photo: "ID Photo",
    baseSalary: "Base salary (optional)",
    familyStatus: "Family status",
    selectFamilyStatus: "Select status",
    childrenCount: "Number of children",
    socialSecurityNumber: "Social Security Number (optional)",
    contractStatus: "Contract status",
    selectContractStatus: "Select status",
    clientAccountInfo: "Client Account Info",
    insurerOptional: "Insurer (optional)",
    noInsurer: "No insurer",
    autoDiscountRate: "Auto discount rate (%)",
    debtLimit: "Debt limit",
    canTakeVoucher: "Can take vouchers",
    agentRate: "Agent rate (%)",
    beneficiaryRate: "Beneficiary rate (%)",
    moderatorTicketRate: "Moderator ticket rate (%)",
    deposit: "Deposit",
    // Contract Types
    cdi: "Permanent Contract",
    cdd: "Fixed-term Contract",
    internship: "Internship",
    freelance: "Freelance",
    // Family Statuses
    single: "Single",
    married: "Married",
    divorced: "Divorced",
    widowed: "Widowed",
    // Job Functions
    pharmacistOwner: "Owner Pharmacist",
    assistantPharmacist: "Assistant Pharmacist",
    preparer: "Preparer",
    technician: "Technician",
    cashier: "Cashier",
    seller: "Seller",
    stockManager: "Stock Manager",
    accountant: "Accountant",
    secretary: "Secretary",
    deliveryPerson: "Delivery Person",
    intern: "Intern",
    // Employee Filters
    filterByFunction: "Filter by function",
    filterByStatus: "Filter by status",
    filterByFamilyStatus: "Filter by family status",
    minSalary: "Minimum salary",
    maxSalary: "Maximum salary",
    clearFilters: "Clear filters",
    filters: "Filters",
    // Schedule Management
    scheduleManagement: "Schedule Management",
    scheduleManagementDesc: "Plan your employees' work schedules",
    newSchedule: "New schedule",
    editSchedule: "Edit schedule",
    date: "Date",
    startTime: "Start time",
    endTime: "End time",
    shiftType: "Shift type",
    post: "Post/Zone",
    scheduleStatus: "Status",
    notes: "Notes",
    morning: "Morning",
    afternoon: "Afternoon",
    night: "Night",
    full: "Full day",
    planned: "Planned",
    confirmed: "Confirmed",
    cancelled: "Cancelled",
    scheduleCreated: "Schedule created successfully",
    scheduleUpdated: "Schedule updated successfully",
    scheduleDeleted: "Schedule deleted successfully",
    noScheduleFound: "No schedule found",
    loadingSchedules: "Loading schedules...",
    // Leave Management
    leaveManagement: "Leave Management",
    leaveManagementDesc: "Manage your employees' leave requests",
    newLeaveRequest: "New leave request",
    editLeaveRequest: "Edit request",
    leaveType: "Leave type",
    startDate: "Start date",
    endDate: "End date",
    reason: "Reason",
    comments: "Comments",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    paidLeave: "Paid leave",
    unpaidLeave: "Unpaid leave",
    sickLeave: "Sick leave",
    maternityLeave: "Maternity leave",
    paternityLeave: "Paternity leave",
    leaveCreated: "Leave request created successfully",
    leaveUpdated: "Leave request updated successfully",
    leaveDeleted: "Leave request deleted",
    noLeaveFound: "No leave request found",
    loadingLeaves: "Loading leave requests...",
    // Training Management
    trainingManagement: "Training Management",
    trainingManagementDesc: "Organize training for your employees",
    newTraining: "New training",
    editTraining: "Edit training",
    trainingName: "Training name",
    trainingDescription: "Description",
    trainingStartDate: "Start date",
    trainingEndDate: "End date",
    duration: "Duration",
    location: "Location",
    cost: "Cost",
    participants: "Participants",
    addParticipant: "Add participant",
    removeParticipant: "Remove",
    selectEmployee: "Select an employee",
    trainingStatus: "Status",
    scheduled: "Scheduled",
    inProgress: "In progress",
    completed: "Completed",
    trainingCreated: "Training created successfully",
    trainingUpdated: "Training updated successfully",
    trainingDeleted: "Training deleted",
    noTrainingFound: "No training found",
    loadingTrainings: "Loading training...",
    // Partner Module
    partnersOverview: "Overview",
    insurers: "Insurers",
    companies: "Companies",
    conventioned: "Conventioned",
    suppliers: "Suppliers",
    laboratories: "Laboratories",
    insuranceCompanies: "Insurance companies",
    partnerCompanies: "Partner companies",
    conventionedEstablishments: "Conventioned establishments",
    activeSuppliers: "Active suppliers",
    pharmaLabs: "Pharmaceutical laboratories",
    recentPartners: "Recent Partners",
    addedAgo: "Added",
    days: "days ago",
    week: "week ago",
    weeks: "weeks ago",
    manageInsurers: "Manage Insurers",
    manageSuppliers: "Manage Suppliers",
    manageLabs: "Manage Laboratories",
    // Insurance Manager
    insurerManagement: "Insurer Management",
    newInsurer: "New Insurer",
    editInsurer: "Edit insurer",
    searchInsurer: "Search for an insurer...",
    insurerName: "Insurer name",
    niu: "Tax ID",
    insurerAdded: "Insurer added successfully",
    insurerModified: "Insurer modified successfully",
    insurerDeleted: "Insurer deleted",
    noInsurerFound: "No insurer found",
    contacts: "Contacts",
    notProvided: "Not provided",
    actions: "Actions",
    // Supplier Manager
    supplierManagement: "Supplier Management",
    newSupplier: "New Supplier",
    editSupplier: "Edit supplier",
    searchSupplier: "Search for a supplier...",
    supplierName: "Supplier name",
    supplierAdded: "Supplier added successfully",
    supplierModified: "Supplier modified successfully",
    supplierDeleted: "Supplier deleted",
    noSupplierFound: "No supplier found",
    // Laboratory Manager
    laboratoryManagement: "Laboratory Management",
    newLaboratory: "New Laboratory",
    editLaboratory: "Edit laboratory",
    searchLaboratory: "Search for a laboratory...",
    laboratoryName: "Laboratory name",
    laboratoryAdded: "Laboratory added successfully",
    laboratoryModified: "Laboratory modified successfully",
    laboratoryDeleted: "Laboratory deleted",
    noLaboratoryFound: "No laboratory found",
    // Company Manager
    companyManagement: "Company Management",
    newCompany: "New Company",
    editCompany: "Edit company",
    searchCompany: "Search for a company...",
    companyName: "Company name",
    companyAdded: "Company added successfully",
    companyModified: "Company modified successfully",
    companyDeleted: "Company deleted",
    noCompanyFound: "No company found",
    // Conventioned Manager
    conventionedManagement: "Conventioned Management",
    newConventioned: "New Conventioned",
    editConventioned: "Edit conventioned",
    searchConventioned: "Search for a conventioned...",
    conventionedName: "Conventioned name",
    conventionedAdded: "Conventioned added successfully",
    conventionedModified: "Conventioned modified successfully",
    conventionedDeleted: "Conventioned deleted",
    noConventionedFound: "No conventioned found",
    // Referentiel Module
    referentielOverview: "Overview",
    catalog: "Catalog",
    forms: "Forms",
    families: "Families",
    shelves: "Shelves",
    categories: "Categories",
    dci: "INN",
    therapeuticClasses: "Therapeutic classes",
    regulations: "Regulations",
    referencedProducts: "Referenced products",
    productFamilies: "Product families",
    galenicForms: "Galenic forms",
    organizationalShelves: "Organizational shelves",
    pricingCategories: "Pricing categories",
    activeIngredients: "Active ingredients",
    regulatoryStatuses: "Regulatory statuses",
    recentProducts: "Recent Products",
    addedOn: "Added",
    product: "Product",
    noRecentProduct: "No recent products",
    manageCatalog: "Manage Catalog",
    manageFamilies: "Manage Families",
    manageCategories: "Manage Categories",
    // Family Manager
    familyManagementTitle: "Product Families",
    newFamily: "Add",
    editFamily: "Edit family",
    addFamily: "Add a family",
    searchFamily: "Search for a family...",
    familyLabel: "Family label",
    description: "Description",
    familyAdded: "Family added successfully",
    familyModified: "Family modified successfully",
    familyDeleted: "Family deleted successfully",
    noFamilyFound: "No family found",
    label: "Label",
    // Formes Manager
    formesManagementTitle: "Galenic Forms",
    newForm: "Add",
    editForm: "Edit form",
    searchForm: "Search for a form...",
    formLabel: "Form label",
    formAdded: "Form added successfully",
    formModified: "Form modified successfully",
    formDeleted: "Form deleted successfully",
    noFormFound: "No form found",
    // Rayon Manager
    rayonManagementTitle: "Product Shelves",
    newRayon: "Add Shelf",
    editRayon: "Edit shelf",
    searchRayon: "Search for a shelf...",
    rayonLabel: "Shelf label",
    rayonAdded: "Shelf added successfully",
    rayonModified: "Shelf modified successfully",
    rayonDeleted: "Shelf deleted successfully",
    noRayonFound: "No shelf found",
    // DCI Manager
    dciManagementTitle: "International Nonproprietary Names",
    newDci: "Add",
    editDci: "Edit INN",
    searchDci: "Search for an INN...",
    dciLabel: "INN label",
    dciAdded: "INN added successfully",
    dciModified: "INN modified successfully",
    dciDeleted: "INN deleted successfully",
    noDciFound: "No INN found",
    // Therapeutic Class Manager
    therapeuticClassManagementTitle: "Therapeutic Classes",
    newTherapeuticClass: "Add",
    editTherapeuticClass: "Edit class",
    searchTherapeuticClass: "Search for a class...",
    therapeuticClassLabel: "Class label",
    therapeuticClassAdded: "Class added successfully",
    therapeuticClassModified: "Class modified successfully",
    therapeuticClassDeleted: "Class deleted successfully",
    noTherapeuticClassFound: "No class found",
    // Pricing Categories
    pricingCategoriesTitle: "Pricing Categories",
    newCategory: "Add",
    editCategory: "Edit category",
    searchCategory: "Search for a category...",
    categoryLabel: "Category label",
    categoryAdded: "Category added successfully",
    categoryModified: "Category modified successfully",
    categoryDeleted: "Category deleted successfully",
    noCategoryFound: "No category found",
    // Regulation Tracker
    regulationTrackerTitle: "Regulations",
    newRegulation: "Add",
    editRegulation: "Edit regulation",
    searchRegulation: "Search for a regulation...",
    regulationLabel: "Regulation label",
    regulationAdded: "Regulation added successfully",
    regulationModified: "Regulation modified successfully",
    regulationDeleted: "Regulation deleted successfully",
    noRegulationFound: "No regulation found",
    // Product Catalog
    productCatalogTitle: "Product Catalog",
    newProduct: "New Product",
    editProduct: "Edit product",
    searchProduct: "Search for a product...",
    productName: "Product name",
    productAdded: "Product added successfully",
    productModified: "Product modified successfully",
    productDeleted: "Product deleted successfully",
    noProductFound: "No product found",
    // Client Module
    clientsOverview: "Analytics",
    clients: "Clients",
    clientModuleTitle: "Client Management",
    clientModuleDesc: "View and manage all your clients",
    clientCreation: "Client creation",
    clientCreationInfo: "Client accounts are created automatically from the modules",
    personnelModule: "Personnel",
    companyModule: "Company",
    conventionedModule: "Conventioned",
    searchClient: "Search for a client...",
    totalClients: "Total clients",
    noClientFound: "No client found for this search",
    noClientRegistered: "No clients registered",
    loadingClients: "Loading clients...",
    discountRate: "Discount rate",
    clientType: "Client type",
    confirmDeleteClient: "Are you sure you want to delete this client?",
    clientUpdated: "Client updated successfully",
    clientDeleted: "Client deleted successfully",
    ordinary: "Ordinary",
    // Common Actions
    cancel: "Cancel",
    save: "Save",
    create: "Create",
    modify: "Modify",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    close: "Close",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    export: "Export",
    import: "Import",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    reset: "Reset",
    processing: "Processing...",
    errorLoading: "Error loading data",
    requiredField: "This field is required",
    // Table Headers
    name: "Name",
    status: "Status",
    createdAt: "Created at",
    updatedAt: "Updated at",
  },
  es: {
    // Header
    features: "Características",
    modules: "Módulos",
    ai: "Inteligencia Artificial",
    contact: "Contacto",
    freeTrial: "Prueba Gratuita",
    dashboard: "Panel de control",
    signOut: "Cerrar sesión",
    connectPharmacy: "Conectar farmacia",
    disconnectPharmacy: "Desconectar farmacia",
    pharmacy: "Farmacia",
    // Hero
    heroTitle: "Solución Completa de Gestión Farmacéutica",
    heroTagline: "La solución completa para su farmacia",
    heroTransformTitle1: "Transforme la gestión",
    heroTransformTitle2: "de su farmacia",
    heroDescription: "PharmaSoft es una aplicación completa de gestión de farmacias disponible en versión web y móvil, diseñada para simplificar todos sus procesos.",
    connectYourPharmacy: "Conectar su Farmacia",
    loading: "Cargando...",
    seeDemo: "Ver Demo",
    pharmaciesUsing: "farmacias ya usan PharmaSoft",
    stocks: "Inventario",
    optimal: "Óptimo",
    attention: "Atención",
    critical: "Crítico",
    products: "productos",
    availability: "disponibilidad",
    sales: "Ventas",
    activeSession: "Sesión activa",
    // Features
    featuresTitle: "Todas las funciones en una sola solución",
    featuresSubtitle: "Pharmasoft revoluciona la gestión de su farmacia con un conjunto completo de herramientas integradas e innovadoras.",
    salesManagement: "Gestión de Ventas",
    salesDesc: "Punto de venta táctil, gestión de recetas, descuentos y promociones automatizadas.",
    stockManagement: "Gestión de Inventario",
    stockDesc: "Inventario en tiempo real, alertas de umbral, pedidos automatizados, seguimiento de caducidad.",
    clientManagement: "Gestión de Clientes",
    clientDesc: "Base de datos de clientes, historial de compras, programa de fidelidad, segmentación.",
    cashManagement: "Gestión de Caja",
    cashDesc: "Multi-cajas, seguimiento de pagos, cierres diarios, informes detallados.",
    analytics: "Análisis e Informes",
    analyticsDesc: "Tableros analíticos, informes personalizados, previsiones y tendencias.",
    security: "Seguridad Avanzada",
    securityDesc: "Autenticación multifactor, gestión detallada de derechos de acceso, cifrado de datos.",
    webMobile: "Web y Móvil",
    webMobileDesc: "Aplicación web responsive y aplicaciones móviles nativas (iOS y Android).",
    multilingual: "Multilingüe",
    multilingualDesc: "Aplicación disponible en 4 idiomas: Francés, Inglés, Español y Lingala.",
    voiceCommands: "Comandos de Voz",
    voiceDesc: "Controle la aplicación por voz, dictado de voz y reconocimiento de medicamentos.",
    // Footer
    footerDescription: "Una aplicación completa de gestión de farmacias disponible en versión web y móvil.",
    quickLinks: "Enlaces Rápidos",
    contactUs: "Contáctenos",
    newsletter: "Suscripción al Boletín",
    newsletterDesc: "Reciba las últimas actualizaciones y ofertas especiales.",
    email: "Su email",
    subscribe: "Suscribirse",
    pricing: "Precios",
    blog: "Blog",
    termsOfUse: "Términos de Uso",
    privacyPolicy: "Política de Privacidad",
    legalNotice: "Aviso Legal",
    allRightsReserved: "Todos los derechos reservados.",
    // Dashboard - Main
    dashboardTitle: "Panel de Control",
    refresh: "Actualizar",
    // Dashboard - Sales Metrics
    dailySalesTitle: "Ventas del Día",
    monthlySalesTitle: "Ingresos Mensuales",
    dailyTransactions: "Transacciones Diarias",
    averageBasket: "Cesta Promedio",
    vsYesterday: "vs ayer",
    thisMonth: "Este mes",
    salesCompleted: "Ventas realizadas",
    perTransaction: "Por transacción",
    // Dashboard - Stock Metrics
    totalStockValue: "Valor Total del Stock",
    availableProducts: "Productos Disponibles",
    lowStockAlerts: "Alertas de Stock Bajo",
    outOfStock: "Sin Stock",
    totalInventory: "Inventario total",
    sufficientStock: "Stock suficiente",
    toReorder: "Para reabastecer",
    stockDepleted: "Stock agotado",
    // Dashboard - Quick Actions
    quickActions: "Acciones Rápidas",
    newSale: "Nueva Venta",
    openRegister: "Abrir Caja",
    payment: "Pago",
    inventory: "Inventario",
    reports: "Informes",
    pos: "Punto de Venta",
    cashManagementAction: "Gestión de Caja",
    collections: "Cobros",
    stockManagementAction: "Gestión de Stock",
    // Dashboard - Critical Alerts
    criticalAlerts: "Alertas Críticas",
    noCriticalAlerts: "Sin alertas críticas",
    units: "unidades",
    unknownDate: "Fecha desconocida",
    expiresOn: "Expira el",
    // Dashboard - Recent Activities
    recentActivities: "Actividades Recientes",
    noRecentActivities: "Sin actividades recientes",
    newSaleActivity: "Nueva venta",
    saleModified: "Venta modificada",
    saleDeleted: "Venta eliminada",
    supplierReception: "Recepción de proveedor",
    receptionUpdated: "Recepción actualizada",
    receptionDeleted: "Recepción eliminada",
    inventoryCreated: "Inventario creado",
    inventoryUpdated: "Inventario actualizado",
    inventoryDeleted: "Inventario eliminado",
    registerOpened: "Sesión de caja abierta",
    registerUpdated: "Sesión de caja actualizada",
    registerDeleted: "Sesión de caja eliminada",
    // Dashboard - Top Products
    topProducts: "Productos Más Vendidos",
    noTopProducts: "Sin productos vendidos",
    soldUnits: "vendidos",
    // Dashboard - Active Sessions
    activeSessions: "Sesiones de Caja Activas",
    noActiveSessions: "Sin sesiones activas",
    openingBalance: "Fondo de caja",
    currentAmount: "Monto actual",
    salesCount: "Ventas",
    // Dashboard - Credit & Promotions
    clientCredit: "Crédito de Clientes",
    totalOngoing: "Total en curso",
    activeAccounts: "Cuentas activas",
    paymentDelays: "Retrasos de pago",
    utilizationRate: "Tasa de utilización",
    promotions: "Promociones",
    active: "Activas",
    usages: "Usos",
    savingsToday: "Ahorros hoy",
    // Sidebar Menu
    mainMenu: "Principal",
    administration: "Administración",
    stock: "Stock",
    salesMenu: "Ventas",
    accounting: "Contabilidad",
    reportsMenu: "Informes",
    aiAssistant: "Asistente IA",
    chatNetwork: "Chat-PharmaSoft",
    settings: "Configuración",
    testsMenu: "Pruebas y Desarrollo",
    testSuites: "Suites de Pruebas",
    signOutLabel: "Cerrar Sesión",
    logoutSuccess: "Ha cerrado sesión correctamente.",
    // General
    dailySales: "Ventas Diarias",
    customerServices: "Servicios al Cliente",
    productsToRenew: "Productos para Renovar",
    last7Days: "Ventas de los últimos 7 días",
    upcomingAppointments: "Próximas Citas",
    help: "Ayuda",
    logout: "Cerrar Sesión",
    // Help Center
    helpCenter: "Centro de Ayuda",
    searchHelp: "Buscar en la ayuda...",
    recentlyViewed: "Visto Recientemente",
    helpModules: "Módulos",
    quickFAQ: "FAQ Rápida",
    videoTutorials: "Tutoriales en Video",
    wasHelpful: "¿Te fue útil este artículo?",
    noResults: "Sin resultados",
    searchTip: "Consejo: prueba palabras clave diferentes",
    relatedArticles: "Artículos Relacionados",
    stepByStep: "Paso a Paso",
    viewAllTutorials: "Ver todos los tutoriales",
    // Sales module translations
    searchProducts: "Buscar productos por nombre o categoría",
    searchPlaceholder: "Buscar un medicamento...",
    noProductsFound: "No se encontraron productos",
    inStock: "En stock",
    add: "Añadir",
    cart: "Carrito",
    emptyCart: "Tu carrito está vacío",
    itemsInCart: "artículos en el carrito",
    itemInCart: "artículo en el carrito",
    cartEmpty: "Añade productos a tu carrito",
    total: "Total",
    checkout: "Finalizar venta",
    // ====================== ADMINISTRATION MODULE ======================
    // Personnel Module
    personnelManagement: "Gestión de Personal",
    personnelDescription: "Gestión de empleados, horarios, permisos y formación (excluyendo gestión de usuarios del sistema)",
    noPermission: "No tiene los permisos necesarios para acceder a este módulo.",
    employees: "Empleados",
    schedules: "Horarios",
    leaves: "Permisos",
    trainings: "Formación",
    // Employee Management
    employeeManagement: "Gestión de Empleados",
    employeeManagementDesc: "Gestione la información personal y profesional de sus empleados",
    newEmployee: "Nuevo Empleado",
    editEmployee: "Editar empleado",
    createEmployee: "Crear un nuevo empleado",
    searchEmployee: "Buscar un empleado...",
    totalEmployees: "Total empleados",
    employeeCreated: "Empleado creado con éxito",
    employeeUpdated: "Empleado actualizado con éxito",
    employeeDeleted: "Empleado eliminado con éxito",
    noEmployeeFound: "No se encontró ningún empleado para esta búsqueda",
    noEmployeeRegistered: "No hay empleados registrados",
    confirmDeleteEmployee: "¿Está seguro de que desea eliminar este empleado?",
    loadingEmployees: "Cargando empleados...",
    formValidationError: "Error de validación del formulario. Por favor, verifique todos los campos.",
    // Employee Form Labels
    lastName: "Apellidos",
    firstName: "Nombre",
    function: "Función",
    selectFunction: "Seleccionar una función",
    address: "Dirección",
    addressOptional: "Dirección (opcional)",
    phone: "Teléfono",
    whatsapp: "WhatsApp (opcional)",
    nationalId: "DNI/NIE",
    profession: "Profesión (opcional)",
    birthDate: "Fecha de nacimiento",
    hireDate: "Fecha de contratación",
    photo: "Foto de identidad",
    baseSalary: "Salario base (opcional)",
    familyStatus: "Estado civil",
    selectFamilyStatus: "Seleccionar estado",
    childrenCount: "Número de hijos",
    socialSecurityNumber: "Número de Seguridad Social (opcional)",
    contractStatus: "Estado del contrato",
    selectContractStatus: "Seleccionar estado",
    clientAccountInfo: "Info Cuenta Cliente",
    insurerOptional: "Asegurador (opcional)",
    noInsurer: "Sin asegurador",
    autoDiscountRate: "Tasa de descuento auto (%)",
    debtLimit: "Límite de deuda",
    canTakeVoucher: "Puede tomar vales",
    agentRate: "Tasa agente (%)",
    beneficiaryRate: "Tasa beneficiario (%)",
    moderatorTicketRate: "Tasa ticket moderador (%)",
    deposit: "Depósito",
    // Contract Types
    cdi: "Contrato indefinido",
    cdd: "Contrato temporal",
    internship: "Prácticas",
    freelance: "Autónomo",
    // Family Statuses
    single: "Soltero/a",
    married: "Casado/a",
    divorced: "Divorciado/a",
    widowed: "Viudo/a",
    // Job Functions
    pharmacistOwner: "Farmacéutico Titular",
    assistantPharmacist: "Farmacéutico Adjunto",
    preparer: "Preparador",
    technician: "Técnico",
    cashier: "Cajero",
    seller: "Vendedor",
    stockManager: "Gestor de inventario",
    accountant: "Contable",
    secretary: "Secretario",
    deliveryPerson: "Repartidor",
    intern: "Becario",
    // Employee Filters
    filterByFunction: "Filtrar por función",
    filterByStatus: "Filtrar por estado",
    filterByFamilyStatus: "Filtrar por estado civil",
    minSalary: "Salario mínimo",
    maxSalary: "Salario máximo",
    clearFilters: "Borrar filtros",
    filters: "Filtros",
    // Schedule Management
    scheduleManagement: "Gestión de Horarios",
    scheduleManagementDesc: "Planifique los horarios de trabajo de sus empleados",
    newSchedule: "Nuevo horario",
    editSchedule: "Editar horario",
    date: "Fecha",
    startTime: "Hora de inicio",
    endTime: "Hora de fin",
    shiftType: "Tipo de turno",
    post: "Puesto/Zona",
    scheduleStatus: "Estado",
    notes: "Notas",
    morning: "Mañana",
    afternoon: "Tarde",
    night: "Noche",
    full: "Jornada completa",
    planned: "Planificado",
    confirmed: "Confirmado",
    cancelled: "Cancelado",
    scheduleCreated: "Horario creado con éxito",
    scheduleUpdated: "Horario actualizado con éxito",
    scheduleDeleted: "Horario eliminado con éxito",
    noScheduleFound: "No se encontró ningún horario",
    loadingSchedules: "Cargando horarios...",
    // Leave Management
    leaveManagement: "Gestión de Permisos",
    leaveManagementDesc: "Gestione las solicitudes de permisos de sus empleados",
    newLeaveRequest: "Nueva solicitud de permiso",
    editLeaveRequest: "Editar solicitud",
    leaveType: "Tipo de permiso",
    startDate: "Fecha de inicio",
    endDate: "Fecha de fin",
    reason: "Motivo",
    comments: "Comentarios",
    pending: "Pendiente",
    approved: "Aprobado",
    rejected: "Rechazado",
    paidLeave: "Permiso remunerado",
    unpaidLeave: "Permiso no remunerado",
    sickLeave: "Baja por enfermedad",
    maternityLeave: "Permiso de maternidad",
    paternityLeave: "Permiso de paternidad",
    leaveCreated: "Solicitud de permiso creada con éxito",
    leaveUpdated: "Solicitud de permiso actualizada con éxito",
    leaveDeleted: "Solicitud de permiso eliminada",
    noLeaveFound: "No se encontró ninguna solicitud de permiso",
    loadingLeaves: "Cargando permisos...",
    // Training Management
    trainingManagement: "Gestión de Formación",
    trainingManagementDesc: "Organice la formación para sus empleados",
    newTraining: "Nueva formación",
    editTraining: "Editar formación",
    trainingName: "Nombre de la formación",
    trainingDescription: "Descripción",
    trainingStartDate: "Fecha de inicio",
    trainingEndDate: "Fecha de fin",
    duration: "Duración",
    location: "Ubicación",
    cost: "Coste",
    participants: "Participantes",
    addParticipant: "Añadir participante",
    removeParticipant: "Eliminar",
    selectEmployee: "Seleccionar un empleado",
    trainingStatus: "Estado",
    scheduled: "Programada",
    inProgress: "En curso",
    completed: "Completada",
    trainingCreated: "Formación creada con éxito",
    trainingUpdated: "Formación actualizada con éxito",
    trainingDeleted: "Formación eliminada",
    noTrainingFound: "No se encontró ninguna formación",
    loadingTrainings: "Cargando formaciones...",
    // Partner Module
    partnersOverview: "Vista general",
    insurers: "Aseguradores",
    companies: "Empresas",
    conventioned: "Convencionados",
    suppliers: "Proveedores",
    laboratories: "Laboratorios",
    insuranceCompanies: "Compañías de seguros",
    partnerCompanies: "Empresas asociadas",
    conventionedEstablishments: "Establecimientos convencionados",
    activeSuppliers: "Proveedores activos",
    pharmaLabs: "Laboratorios farmacéuticos",
    recentPartners: "Socios Recientes",
    addedAgo: "Añadido hace",
    days: "días",
    week: "semana",
    weeks: "semanas",
    manageInsurers: "Gestionar Aseguradores",
    manageSuppliers: "Gestionar Proveedores",
    manageLabs: "Gestionar Laboratorios",
    // Insurance Manager
    insurerManagement: "Gestión de Aseguradores",
    newInsurer: "Nuevo Asegurador",
    editInsurer: "Editar asegurador",
    searchInsurer: "Buscar un asegurador...",
    insurerName: "Nombre del asegurador",
    niu: "NIF",
    insurerAdded: "Asegurador añadido con éxito",
    insurerModified: "Asegurador modificado con éxito",
    insurerDeleted: "Asegurador eliminado",
    noInsurerFound: "No se encontró ningún asegurador",
    contacts: "Contactos",
    notProvided: "No proporcionado",
    actions: "Acciones",
    // Supplier Manager
    supplierManagement: "Gestión de Proveedores",
    newSupplier: "Nuevo Proveedor",
    editSupplier: "Editar proveedor",
    searchSupplier: "Buscar un proveedor...",
    supplierName: "Nombre del proveedor",
    supplierAdded: "Proveedor añadido con éxito",
    supplierModified: "Proveedor modificado con éxito",
    supplierDeleted: "Proveedor eliminado",
    noSupplierFound: "No se encontró ningún proveedor",
    // Laboratory Manager
    laboratoryManagement: "Gestión de Laboratorios",
    newLaboratory: "Nuevo Laboratorio",
    editLaboratory: "Editar laboratorio",
    searchLaboratory: "Buscar un laboratorio...",
    laboratoryName: "Nombre del laboratorio",
    laboratoryAdded: "Laboratorio añadido con éxito",
    laboratoryModified: "Laboratorio modificado con éxito",
    laboratoryDeleted: "Laboratorio eliminado",
    noLaboratoryFound: "No se encontró ningún laboratorio",
    // Company Manager
    companyManagement: "Gestión de Empresas",
    newCompany: "Nueva Empresa",
    editCompany: "Editar empresa",
    searchCompany: "Buscar una empresa...",
    companyName: "Nombre de la empresa",
    companyAdded: "Empresa añadida con éxito",
    companyModified: "Empresa modificada con éxito",
    companyDeleted: "Empresa eliminada",
    noCompanyFound: "No se encontró ninguna empresa",
    // Conventioned Manager
    conventionedManagement: "Gestión de Convencionados",
    newConventioned: "Nuevo Convencionado",
    editConventioned: "Editar convencionado",
    searchConventioned: "Buscar un convencionado...",
    conventionedName: "Nombre del convencionado",
    conventionedAdded: "Convencionado añadido con éxito",
    conventionedModified: "Convencionado modificado con éxito",
    conventionedDeleted: "Convencionado eliminado",
    noConventionedFound: "No se encontró ningún convencionado",
    // Referentiel Module
    referentielOverview: "Vista general",
    catalog: "Catálogo",
    forms: "Formas",
    families: "Familias",
    shelves: "Estantes",
    categories: "Categorías",
    dci: "DCI",
    therapeuticClasses: "Clases terapéuticas",
    regulations: "Regulaciones",
    referencedProducts: "Productos referenciados",
    productFamilies: "Familias de productos",
    galenicForms: "Formas galénicas",
    organizationalShelves: "Estantes organizacionales",
    pricingCategories: "Categorías de precios",
    activeIngredients: "Principios activos",
    regulatoryStatuses: "Estados regulatorios",
    recentProducts: "Productos Recientes",
    addedOn: "Añadido el",
    product: "Producto",
    noRecentProduct: "No hay productos recientes",
    manageCatalog: "Gestionar Catálogo",
    manageFamilies: "Gestionar Familias",
    manageCategories: "Gestionar Categorías",
    // Family Manager
    familyManagementTitle: "Familias de Productos",
    newFamily: "Añadir",
    editFamily: "Editar familia",
    addFamily: "Añadir una familia",
    searchFamily: "Buscar una familia...",
    familyLabel: "Etiqueta de familia",
    description: "Descripción",
    familyAdded: "Familia añadida con éxito",
    familyModified: "Familia modificada con éxito",
    familyDeleted: "Familia eliminada con éxito",
    noFamilyFound: "No se encontró ninguna familia",
    label: "Etiqueta",
    // Formes Manager
    formesManagementTitle: "Formas Galénicas",
    newForm: "Añadir",
    editForm: "Editar forma",
    searchForm: "Buscar una forma...",
    formLabel: "Etiqueta de forma",
    formAdded: "Forma añadida con éxito",
    formModified: "Forma modificada con éxito",
    formDeleted: "Forma eliminada con éxito",
    noFormFound: "No se encontró ninguna forma",
    // Rayon Manager
    rayonManagementTitle: "Estantes de Productos",
    newRayon: "Añadir Estante",
    editRayon: "Editar estante",
    searchRayon: "Buscar un estante...",
    rayonLabel: "Etiqueta del estante",
    rayonAdded: "Estante añadido con éxito",
    rayonModified: "Estante modificado con éxito",
    rayonDeleted: "Estante eliminado con éxito",
    noRayonFound: "No se encontró ningún estante",
    // DCI Manager
    dciManagementTitle: "Denominaciones Comunes Internacionales",
    newDci: "Añadir",
    editDci: "Editar DCI",
    searchDci: "Buscar un DCI...",
    dciLabel: "Etiqueta del DCI",
    dciAdded: "DCI añadido con éxito",
    dciModified: "DCI modificado con éxito",
    dciDeleted: "DCI eliminado con éxito",
    noDciFound: "No se encontró ningún DCI",
    // Therapeutic Class Manager
    therapeuticClassManagementTitle: "Clases Terapéuticas",
    newTherapeuticClass: "Añadir",
    editTherapeuticClass: "Editar clase",
    searchTherapeuticClass: "Buscar una clase...",
    therapeuticClassLabel: "Etiqueta de clase",
    therapeuticClassAdded: "Clase añadida con éxito",
    therapeuticClassModified: "Clase modificada con éxito",
    therapeuticClassDeleted: "Clase eliminada con éxito",
    noTherapeuticClassFound: "No se encontró ninguna clase",
    // Pricing Categories
    pricingCategoriesTitle: "Categorías de Precios",
    newCategory: "Añadir",
    editCategory: "Editar categoría",
    searchCategory: "Buscar una categoría...",
    categoryLabel: "Etiqueta de categoría",
    categoryAdded: "Categoría añadida con éxito",
    categoryModified: "Categoría modificada con éxito",
    categoryDeleted: "Categoría eliminada con éxito",
    noCategoryFound: "No se encontró ninguna categoría",
    // Regulation Tracker
    regulationTrackerTitle: "Regulaciones",
    newRegulation: "Añadir",
    editRegulation: "Editar regulación",
    searchRegulation: "Buscar una regulación...",
    regulationLabel: "Etiqueta de regulación",
    regulationAdded: "Regulación añadida con éxito",
    regulationModified: "Regulación modificada con éxito",
    regulationDeleted: "Regulación eliminada con éxito",
    noRegulationFound: "No se encontró ninguna regulación",
    // Product Catalog
    productCatalogTitle: "Catálogo de Productos",
    newProduct: "Nuevo Producto",
    editProduct: "Editar producto",
    searchProduct: "Buscar un producto...",
    productName: "Nombre del producto",
    productAdded: "Producto añadido con éxito",
    productModified: "Producto modificado con éxito",
    productDeleted: "Producto eliminado con éxito",
    noProductFound: "No se encontró ningún producto",
    // Client Module
    clientsOverview: "Analíticas",
    clients: "Clientes",
    clientModuleTitle: "Gestión de Clientes",
    clientModuleDesc: "Consulte y gestione todos sus clientes",
    clientCreation: "Creación de clientes",
    clientCreationInfo: "Las cuentas de clientes se crean automáticamente desde los módulos",
    personnelModule: "Personal",
    companyModule: "Empresa",
    conventionedModule: "Convencionado",
    searchClient: "Buscar un cliente...",
    totalClients: "Total clientes",
    noClientFound: "No se encontró ningún cliente para esta búsqueda",
    noClientRegistered: "No hay clientes registrados",
    loadingClients: "Cargando clientes...",
    discountRate: "Tasa de descuento",
    clientType: "Tipo de cliente",
    confirmDeleteClient: "¿Está seguro de que desea eliminar este cliente?",
    clientUpdated: "Cliente actualizado con éxito",
    clientDeleted: "Cliente eliminado con éxito",
    ordinary: "Ordinario",
    // Common Actions
    cancel: "Cancelar",
    save: "Guardar",
    create: "Crear",
    modify: "Modificar",
    delete: "Eliminar",
    edit: "Editar",
    view: "Ver",
    close: "Cerrar",
    confirm: "Confirmar",
    search: "Buscar",
    filter: "Filtrar",
    export: "Exportar",
    import: "Importar",
    back: "Atrás",
    next: "Siguiente",
    previous: "Anterior",
    submit: "Enviar",
    reset: "Restablecer",
    processing: "Procesando...",
    errorLoading: "Error al cargar los datos",
    requiredField: "Este campo es obligatorio",
    // Table Headers
    name: "Nombre",
    status: "Estado",
    createdAt: "Creado el",
    updatedAt: "Actualizado el",
  },
  ln: {
    // Header
    features: "Bisaleli",
    modules: "Biteni",
    ai: "Mayele ya Masini",
    contact: "Kokutana",
    freeTrial: "Komeka ofele",
    dashboard: "Tableau ya Bobongisi",
    signOut: "Kobima",
    connectPharmacy: "Kokangisa farmasi",
    disconnectPharmacy: "Kolongola farmasi",
    pharmacy: "Farmasi",
    // Hero
    heroTitle: "Ndenge ya kobongisa Farmasi mobimba",
    heroTagline: "Solution mobimba mpo na farmasi na yo",
    heroTransformTitle1: "Bobongola ndenge",
    heroTransformTitle2: "ya kobongisa farmasi na yo",
    heroDescription: "PharmaSoft ezali application mobimba ya kobongisa farmasi ezali na version web pe mobile, esalemi mpo na kosalisa misala na yo nyonso.",
    connectYourPharmacy: "Kokangisa Farmasi na yo",
    loading: "Ezali kokota...",
    seeDemo: "Tala Demo",
    pharmaciesUsing: "ba farmasi basalelaka kala PharmaSoft",
    stocks: "Biloko",
    optimal: "Malamu",
    attention: "Bokebisi",
    critical: "Likama",
    products: "biloko",
    availability: "disponibilité",
    sales: "Boteki",
    activeSession: "Session ezali kosala",
    // Features
    featuresTitle: "Bisaleli nyonso na kati ya solution moko",
    featuresSubtitle: "Pharmasoft ezali kobongola ndenge ya kobongisa farmasi na yo na bisaleli ya sika pe ebongisami malamu.",
    salesManagement: "Bobongisi Boteki",
    salesDesc: "Point ya koteka ya touchscreen, bobongisi prescriptions, réductions pe promotions automatiques.",
    stockManagement: "Bobongisi Biloko",
    stockDesc: "Inventaire ya temps réel, koyebisa taux, commandes automatiques, kolanda biloko ekokufa.",
    clientManagement: "Bobongisi Basombi",
    clientDesc: "Database ya basombi, historique ya boteki, programme ya fidélité, kokabola.",
    cashManagement: "Bobongisi Mbongo",
    cashDesc: "Ba caisse ebele, kolanda bozwi, kokangi mokolo na mokolo, rapport détaillé.",
    analytics: "Analyse & Rapport",
    analyticsDesc: "Tableau de bord analytique, rapport personalisé, prévision pe tendance.",
    security: "Sécurité ya Niveau Likolo",
    securityDesc: "Autentication multifactor, bobongisi malamu ya droits d'accès, cryptage ya données.",
    webMobile: "Web & Mobile",
    webMobileDesc: "Application web responsive pe applications mobiles natif (iOS pe Android).",
    multilingual: "Minoko Ebele",
    multilingualDesc: "Application ezali na minoko 4 : Français, Anglais, Espagnol pe Lingala.",
    voiceCommands: "Mitindo ya Mongongo",
    voiceDesc: "Contrôle application na mongongo, dictée vocale pe reconnaissance ya médicaments.",
    // Footer
    footerDescription: "Application mobimba ya kobongisa farmasi ezali na version web pe mobile.",
    quickLinks: "Liens ya Mbangu",
    contactUs: "Kutana na Biso",
    newsletter: "Inscription na Newsletter",
    newsletterDesc: "Kozwa sango ya sika pe offres spéciales.",
    email: "Email ya yo",
    subscribe: "Inscription",
    pricing: "Ntalo",
    blog: "Blog",
    termsOfUse: "Mibeko ya Kosalela",
    privacyPolicy: "Politiki ya Confidentialité",
    legalNotice: "Mentions Légales",
    allRightsReserved: "Droits nyonso ebatelami.",
    // Dashboard - Main
    dashboardTitle: "Tableau ya Bobongisi",
    refresh: "Kosala Sika",
    // Dashboard - Sales Metrics
    dailySalesTitle: "Boteki ya Mokolo",
    monthlySalesTitle: "Mbongo ya Sanza",
    dailyTransactions: "Misala ya Mokolo",
    averageBasket: "Panier ya Kati",
    vsYesterday: "vs lobi",
    thisMonth: "Sanza oyo",
    salesCompleted: "Boteki esalemi",
    perTransaction: "Na mosala moko",
    // Dashboard - Stock Metrics
    totalStockValue: "Motuya ya Biloko Nyonso",
    availableProducts: "Biloko Ezali",
    lowStockAlerts: "Bokebisi Biloko Moke",
    outOfStock: "Biloko Esili",
    totalInventory: "Inventaire mobimba",
    sufficientStock: "Stock ekoki",
    toReorder: "Ya kotia lisusu",
    stockDepleted: "Stock esili",
    // Dashboard - Quick Actions
    quickActions: "Misala ya Mbangu",
    newSale: "Boteki ya Sika",
    openRegister: "Kofungola Caisse",
    payment: "Kofuta",
    inventory: "Inventaire",
    reports: "Rapports",
    pos: "Esika ya Koteka",
    cashManagementAction: "Bobongisi Caisse",
    collections: "Kozwa Mbongo",
    stockManagementAction: "Bobongisi Stock",
    // Dashboard - Critical Alerts
    criticalAlerts: "Bokebisi ya Likama",
    noCriticalAlerts: "Bokebisi moko te",
    units: "biteni",
    unknownDate: "Date eyebani te",
    expiresOn: "Ekosila na",
    // Dashboard - Recent Activities
    recentActivities: "Misala ya Sika",
    noRecentActivities: "Mosala moko te",
    newSaleActivity: "Boteki ya sika",
    saleModified: "Boteki ebongisami",
    saleDeleted: "Boteki elongwe",
    supplierReception: "Kozwa na fournisseur",
    receptionUpdated: "Réception ebongisami",
    receptionDeleted: "Réception elongwe",
    inventoryCreated: "Inventaire esalemi",
    inventoryUpdated: "Inventaire ebongisami",
    inventoryDeleted: "Inventaire elongwe",
    registerOpened: "Session caisse efungwami",
    registerUpdated: "Session caisse ebongisami",
    registerDeleted: "Session caisse elongwe",
    // Dashboard - Top Products
    topProducts: "Biloko Etekamaka Mingi",
    noTopProducts: "Eloko moko te etekamaki",
    soldUnits: "etekamaki",
    // Dashboard - Active Sessions
    activeSessions: "Sessions Caisse Ezali Kosala",
    noActiveSessions: "Session moko te",
    openingBalance: "Mbongo ya kobanda",
    currentAmount: "Mbongo ya lelo",
    salesCount: "Boteki",
    // Dashboard - Credit & Promotions
    clientCredit: "Crédit ya Basombi",
    totalOngoing: "Total ezali kokende",
    activeAccounts: "Compte ezali kosala",
    paymentDelays: "Kofuta na retard",
    utilizationRate: "Taux ya kosalela",
    promotions: "Promotions",
    active: "Ezali kosala",
    usages: "Kosalela",
    savingsToday: "Kobomba lelo",
    // Sidebar Menu
    mainMenu: "Principal",
    administration: "Administration",
    stock: "Stock",
    salesMenu: "Boteki",
    accounting: "Comptabilité",
    reportsMenu: "Rapports",
    aiAssistant: "Assistant IA",
    chatNetwork: "Chat-PharmaSoft",
    settings: "Paramètres",
    testsMenu: "Tests & Développement",
    testSuites: "Suites ya Tests",
    signOutLabel: "Kobima",
    logoutSuccess: "Obimi malamu.",
    // General
    dailySales: "Boteki ya Mokolo",
    customerServices: "Bisaleli mpo na Basombi",
    productsToRenew: "Biloko ya Kotia Lisusu",
    last7Days: "Boteki ya mikolo 7 eleki",
    upcomingAppointments: "Rendez-vous Ekoya",
    help: "Lisalisi",
    logout: "Kobima",
    // Help Center
    helpCenter: "Esika ya Lisalisi",
    searchHelp: "Koluka na lisalisi...",
    recentlyViewed: "Emonami Sika",
    helpModules: "Biteni",
    quickFAQ: "FAQ ya Mbangu",
    videoTutorials: "Ba Tuto ya Video",
    wasHelpful: "Lisolo oyo esalisaki yo?",
    noResults: "Eloko moko te",
    searchTip: "Toli: meka maloba mosusu",
    relatedArticles: "Masolo ya Bondeko",
    stepByStep: "Etape na Etape",
    viewAllTutorials: "Tala ba tuto nyonso",
    // Sales module translations
    searchProducts: "Koluka biloko na kombo to catégorie",
    searchPlaceholder: "Koluka monganga...",
    noProductsFound: "Eloko moko te emonani",
    inStock: "Ezali",
    add: "Kobakisa",
    cart: "Kitunga",
    emptyCart: "Kitunga na yo ezali mpamba",
    itemsInCart: "biloko na kitunga",
    itemInCart: "eloko na kitunga",
    cartEmpty: "Bakisa biloko na kitunga na yo",
    total: "Totalé",
    checkout: "Kosilisa koteka",
    // ====================== ADMINISTRATION MODULE ======================
    // Personnel Module
    personnelManagement: "Bobongisi Basali",
    personnelDescription: "Bobongisi basali, ngonga, kolemba pe formation (kobanda te kobongisa utilisateurs ya système)",
    noPermission: "Ozali na ndingisa te mpo na kokota na module oyo.",
    employees: "Basali",
    schedules: "Ngonga",
    leaves: "Kolemba",
    trainings: "Formation",
    // Employee Management
    employeeManagement: "Bobongisi Basali",
    employeeManagementDesc: "Bongisa makambo ya personel pe ya mosala ya basali na yo",
    newEmployee: "Mosali ya Sika",
    editEmployee: "Kobongisa mosali",
    createEmployee: "Kosala mosali ya sika",
    searchEmployee: "Koluka mosali...",
    totalEmployees: "Basali nyonso",
    employeeCreated: "Mosali asalemi malamu",
    employeeUpdated: "Mosali abongisami malamu",
    employeeDeleted: "Mosali alongwe malamu",
    noEmployeeFound: "Mosali moko te amonani mpo na koluka oyo",
    noEmployeeRegistered: "Mosali moko te akomami",
    confirmDeleteEmployee: "Olingi kolongola mosali oyo?",
    loadingEmployees: "Kokota basali...",
    formValidationError: "Libunga na formulaire. Tala makambo nyonso.",
    // Employee Form Labels
    lastName: "Kombo",
    firstName: "Prénom",
    function: "Fonction",
    selectFunction: "Pona fonction",
    address: "Adresse",
    addressOptional: "Adresse (soki olingi)",
    phone: "Téléphone",
    whatsapp: "WhatsApp (soki olingi)",
    nationalId: "Numéro ya carte",
    profession: "Métier (soki olingi)",
    birthDate: "Mokolo ya kobotama",
    hireDate: "Mokolo ya kozwa mosala",
    photo: "Foto ya carte",
    baseSalary: "Salaire ya base (soki olingi)",
    familyStatus: "Lolenge ya libala",
    selectFamilyStatus: "Pona lolenge",
    childrenCount: "Motango ya bana",
    socialSecurityNumber: "Numéro CNSS (soki olingi)",
    contractStatus: "Lolenge ya contrat",
    selectContractStatus: "Pona lolenge",
    clientAccountInfo: "Makambo ya Compte Client",
    insurerOptional: "Assureur (soki olingi)",
    noInsurer: "Assureur te",
    autoDiscountRate: "Taux ya remise auto (%)",
    debtLimit: "Limite ya dette",
    canTakeVoucher: "Akoki kozwa bons",
    agentRate: "Taux agent (%)",
    beneficiaryRate: "Taux ayant droit (%)",
    moderatorTicketRate: "Taux ticket modérateur (%)",
    deposit: "Caution",
    // Contract Types
    cdi: "Contrat ya seko",
    cdd: "Contrat ya ntango moke",
    internship: "Stage",
    freelance: "Freelance",
    // Family Statuses
    single: "Mobali/Mwasi te",
    married: "Abalani",
    divorced: "Abomi libala",
    widowed: "Akufisa mobali/mwasi",
    // Job Functions
    pharmacistOwner: "Pharmacien Mokonzi",
    assistantPharmacist: "Pharmacien Mosungi",
    preparer: "Préparateur",
    technician: "Technicien",
    cashier: "Caissier",
    seller: "Motekisi",
    stockManager: "Mobongisi stock",
    accountant: "Comptable",
    secretary: "Secrétaire",
    deliveryPerson: "Momemi",
    intern: "Stagiaire",
    // Employee Filters
    filterByFunction: "Pona fonction",
    filterByStatus: "Pona statut",
    filterByFamilyStatus: "Pona lolenge ya libala",
    minSalary: "Salaire ya moke",
    maxSalary: "Salaire ya likolo",
    clearFilters: "Kolongola filtre",
    filters: "Filtre",
    // Schedule Management
    scheduleManagement: "Bobongisi Ngonga",
    scheduleManagementDesc: "Bongisa ngonga ya mosala ya basali na yo",
    newSchedule: "Ngonga ya sika",
    editSchedule: "Kobongisa ngonga",
    date: "Mokolo",
    startTime: "Ngonga ya kobanda",
    endTime: "Ngonga ya kosila",
    shiftType: "Lolenge ya mosala",
    post: "Poste/Zone",
    scheduleStatus: "Statut",
    notes: "Makomi",
    morning: "Ntongo",
    afternoon: "Mpokwa",
    night: "Butu",
    full: "Mokolo mobimba",
    planned: "Ebongisami",
    confirmed: "Endimami",
    cancelled: "Eboyami",
    scheduleCreated: "Ngonga esalemi malamu",
    scheduleUpdated: "Ngonga ebongisami malamu",
    scheduleDeleted: "Ngonga elongwe malamu",
    noScheduleFound: "Ngonga moko te emonani",
    loadingSchedules: "Kokota ngonga...",
    // Leave Management
    leaveManagement: "Bobongisi Kolemba",
    leaveManagementDesc: "Bongisa ba demandes ya kolemba ya basali na yo",
    newLeaveRequest: "Demande ya kolemba ya sika",
    editLeaveRequest: "Kobongisa demande",
    leaveType: "Lolenge ya kolemba",
    startDate: "Mokolo ya kobanda",
    endDate: "Mokolo ya kosila",
    reason: "Ntina",
    comments: "Makanisi",
    pending: "Ezali kozela",
    approved: "Endimami",
    rejected: "Eboyami",
    paidLeave: "Kolemba na mbongo",
    unpaidLeave: "Kolemba na mbongo te",
    sickLeave: "Kolemba ya maladi",
    maternityLeave: "Kolemba ya mama",
    paternityLeave: "Kolemba ya tata",
    leaveCreated: "Demande ya kolemba esalemi malamu",
    leaveUpdated: "Demande ya kolemba ebongisami malamu",
    leaveDeleted: "Demande ya kolemba elongwe",
    noLeaveFound: "Demande moko te emonani",
    loadingLeaves: "Kokota ba demandes...",
    // Training Management
    trainingManagement: "Bobongisi Formation",
    trainingManagementDesc: "Bongisa formation mpo na basali na yo",
    newTraining: "Formation ya sika",
    editTraining: "Kobongisa formation",
    trainingName: "Kombo ya formation",
    trainingDescription: "Malobeli",
    trainingStartDate: "Mokolo ya kobanda",
    trainingEndDate: "Mokolo ya kosila",
    duration: "Ntango",
    location: "Esika",
    cost: "Motuya",
    participants: "Bazwi",
    addParticipant: "Kobakisa mozwi",
    removeParticipant: "Kolongola",
    selectEmployee: "Pona mosali",
    trainingStatus: "Statut",
    scheduled: "Ebongisami",
    inProgress: "Ezali kokende",
    completed: "Esili",
    trainingCreated: "Formation esalemi malamu",
    trainingUpdated: "Formation ebongisami malamu",
    trainingDeleted: "Formation elongwe",
    noTrainingFound: "Formation moko te emonani",
    loadingTrainings: "Kokota formation...",
    // Partner Module
    partnersOverview: "Vue d'ensemble",
    insurers: "Ba Assureurs",
    companies: "Ba Sociétés",
    conventioned: "Ba Conventionnés",
    suppliers: "Ba Fournisseurs",
    laboratories: "Ba Laboratoires",
    insuranceCompanies: "Ba compagnies ya assurance",
    partnerCompanies: "Ba entreprises partenaires",
    conventionedEstablishments: "Ba établissements conventionnés",
    activeSuppliers: "Ba fournisseurs actifs",
    pharmaLabs: "Ba laboratoires pharmaceutiques",
    recentPartners: "Ba Partenaires ya Sika",
    addedAgo: "Ebakisami",
    days: "mikolo",
    week: "poso",
    weeks: "ba poso",
    manageInsurers: "Bongisa Ba Assureurs",
    manageSuppliers: "Bongisa Ba Fournisseurs",
    manageLabs: "Bongisa Ba Laboratoires",
    // Insurance Manager
    insurerManagement: "Bobongisi Ba Assureurs",
    newInsurer: "Assureur ya Sika",
    editInsurer: "Kobongisa assureur",
    searchInsurer: "Koluka assureur...",
    insurerName: "Kombo ya assureur",
    niu: "NIU",
    insurerAdded: "Assureur ebakisami malamu",
    insurerModified: "Assureur ebongisami malamu",
    insurerDeleted: "Assureur elongwe",
    noInsurerFound: "Assureur moko te emonani",
    contacts: "Contacts",
    notProvided: "Epesamaki te",
    actions: "Misala",
    // Supplier Manager
    supplierManagement: "Bobongisi Ba Fournisseurs",
    newSupplier: "Fournisseur ya Sika",
    editSupplier: "Kobongisa fournisseur",
    searchSupplier: "Koluka fournisseur...",
    supplierName: "Kombo ya fournisseur",
    supplierAdded: "Fournisseur ebakisami malamu",
    supplierModified: "Fournisseur ebongisami malamu",
    supplierDeleted: "Fournisseur elongwe",
    noSupplierFound: "Fournisseur moko te emonani",
    // Laboratory Manager
    laboratoryManagement: "Bobongisi Ba Laboratoires",
    newLaboratory: "Laboratoire ya Sika",
    editLaboratory: "Kobongisa laboratoire",
    searchLaboratory: "Koluka laboratoire...",
    laboratoryName: "Kombo ya laboratoire",
    laboratoryAdded: "Laboratoire ebakisami malamu",
    laboratoryModified: "Laboratoire ebongisami malamu",
    laboratoryDeleted: "Laboratoire elongwe",
    noLaboratoryFound: "Laboratoire moko te emonani",
    // Company Manager
    companyManagement: "Bobongisi Ba Sociétés",
    newCompany: "Société ya Sika",
    editCompany: "Kobongisa société",
    searchCompany: "Koluka société...",
    companyName: "Kombo ya société",
    companyAdded: "Société ebakisami malamu",
    companyModified: "Société ebongisami malamu",
    companyDeleted: "Société elongwe",
    noCompanyFound: "Société moko te emonani",
    // Conventioned Manager
    conventionedManagement: "Bobongisi Ba Conventionnés",
    newConventioned: "Conventionné ya Sika",
    editConventioned: "Kobongisa conventionné",
    searchConventioned: "Koluka conventionné...",
    conventionedName: "Kombo ya conventionné",
    conventionedAdded: "Conventionné ebakisami malamu",
    conventionedModified: "Conventionné ebongisami malamu",
    conventionedDeleted: "Conventionné elongwe",
    noConventionedFound: "Conventionné moko te emonani",
    // Referentiel Module
    referentielOverview: "Vue d'ensemble",
    catalog: "Catalogue",
    forms: "Formes",
    families: "Ba Familles",
    shelves: "Ba Rayons",
    categories: "Ba Catégories",
    dci: "DCI",
    therapeuticClasses: "Ba classes thérapeutiques",
    regulations: "Ba Réglementations",
    referencedProducts: "Biloko référencés",
    productFamilies: "Ba familles ya biloko",
    galenicForms: "Formes galéniques",
    organizationalShelves: "Ba rayons organisationnels",
    pricingCategories: "Ba catégories tarifaires",
    activeIngredients: "Ba principes actifs",
    regulatoryStatuses: "Ba statuts réglementaires",
    recentProducts: "Biloko ya Sika",
    addedOn: "Ebakisami",
    product: "Eloko",
    noRecentProduct: "Eloko ya sika te",
    manageCatalog: "Bongisa Catalogue",
    manageFamilies: "Bongisa Ba Familles",
    manageCategories: "Bongisa Ba Catégories",
    // Family Manager
    familyManagementTitle: "Ba Familles ya Biloko",
    newFamily: "Kobakisa",
    editFamily: "Kobongisa famille",
    addFamily: "Kobakisa famille",
    searchFamily: "Koluka famille...",
    familyLabel: "Kombo ya famille",
    description: "Malobeli",
    familyAdded: "Famille ebakisami malamu",
    familyModified: "Famille ebongisami malamu",
    familyDeleted: "Famille elongwe malamu",
    noFamilyFound: "Famille moko te emonani",
    label: "Kombo",
    // Formes Manager
    formesManagementTitle: "Formes Galéniques",
    newForm: "Kobakisa",
    editForm: "Kobongisa forme",
    searchForm: "Koluka forme...",
    formLabel: "Kombo ya forme",
    formAdded: "Forme ebakisami malamu",
    formModified: "Forme ebongisami malamu",
    formDeleted: "Forme elongwe malamu",
    noFormFound: "Forme moko te emonani",
    // Rayon Manager
    rayonManagementTitle: "Ba Rayons ya Biloko",
    newRayon: "Kobakisa Rayon",
    editRayon: "Kobongisa rayon",
    searchRayon: "Koluka rayon...",
    rayonLabel: "Kombo ya rayon",
    rayonAdded: "Rayon ebakisami malamu",
    rayonModified: "Rayon ebongisami malamu",
    rayonDeleted: "Rayon elongwe malamu",
    noRayonFound: "Rayon moko te emonani",
    // DCI Manager
    dciManagementTitle: "Dénominations Communes Internationales",
    newDci: "Kobakisa",
    editDci: "Kobongisa DCI",
    searchDci: "Koluka DCI...",
    dciLabel: "Kombo ya DCI",
    dciAdded: "DCI ebakisami malamu",
    dciModified: "DCI ebongisami malamu",
    dciDeleted: "DCI elongwe malamu",
    noDciFound: "DCI moko te emonani",
    // Therapeutic Class Manager
    therapeuticClassManagementTitle: "Ba Classes Thérapeutiques",
    newTherapeuticClass: "Kobakisa",
    editTherapeuticClass: "Kobongisa classe",
    searchTherapeuticClass: "Koluka classe...",
    therapeuticClassLabel: "Kombo ya classe",
    therapeuticClassAdded: "Classe ebakisami malamu",
    therapeuticClassModified: "Classe ebongisami malamu",
    therapeuticClassDeleted: "Classe elongwe malamu",
    noTherapeuticClassFound: "Classe moko te emonani",
    // Pricing Categories
    pricingCategoriesTitle: "Ba Catégories Tarifaires",
    newCategory: "Kobakisa",
    editCategory: "Kobongisa catégorie",
    searchCategory: "Koluka catégorie...",
    categoryLabel: "Kombo ya catégorie",
    categoryAdded: "Catégorie ebakisami malamu",
    categoryModified: "Catégorie ebongisami malamu",
    categoryDeleted: "Catégorie elongwe malamu",
    noCategoryFound: "Catégorie moko te emonani",
    // Regulation Tracker
    regulationTrackerTitle: "Ba Réglementations",
    newRegulation: "Kobakisa",
    editRegulation: "Kobongisa réglementation",
    searchRegulation: "Koluka réglementation...",
    regulationLabel: "Kombo ya réglementation",
    regulationAdded: "Réglementation ebakisami malamu",
    regulationModified: "Réglementation ebongisami malamu",
    regulationDeleted: "Réglementation elongwe malamu",
    noRegulationFound: "Réglementation moko te emonani",
    // Product Catalog
    productCatalogTitle: "Catalogue ya Biloko",
    newProduct: "Eloko ya Sika",
    editProduct: "Kobongisa eloko",
    searchProduct: "Koluka eloko...",
    productName: "Kombo ya eloko",
    productAdded: "Eloko ebakisami malamu",
    productModified: "Eloko ebongisami malamu",
    productDeleted: "Eloko elongwe malamu",
    noProductFound: "Eloko moko te emonani",
    // Client Module
    clientsOverview: "Analytics",
    clients: "Ba Clients",
    clientModuleTitle: "Bobongisi Ba Clients",
    clientModuleDesc: "Tala pe bongisa ba clients na yo nyonso",
    clientCreation: "Kosala ba clients",
    clientCreationInfo: "Ba comptes clients esalemaka seul depuis les modules",
    personnelModule: "Personnel",
    companyModule: "Société",
    conventionedModule: "Conventionné",
    searchClient: "Koluka client...",
    totalClients: "Ba clients nyonso",
    noClientFound: "Client moko te amonani mpo na koluka oyo",
    noClientRegistered: "Client moko te akomami",
    loadingClients: "Kokota ba clients...",
    discountRate: "Taux ya remise",
    clientType: "Lolenge ya client",
    confirmDeleteClient: "Olingi kolongola client oyo?",
    clientUpdated: "Client ebongisami malamu",
    clientDeleted: "Client elongwe malamu",
    ordinary: "Ordinaire",
    // Common Actions
    cancel: "Koboya",
    save: "Kobomba",
    create: "Kosala",
    modify: "Kobongisa",
    delete: "Kolongola",
    edit: "Kobongisa",
    view: "Kotala",
    close: "Kokanga",
    confirm: "Kondima",
    search: "Koluka",
    filter: "Filtre",
    export: "Kobimisa",
    import: "Kokotisa",
    back: "Kozonga",
    next: "Ya sima",
    previous: "Ya liboso",
    submit: "Kotinda",
    reset: "Kobanda lisusu",
    processing: "Ezali kosala...",
    errorLoading: "Libunga na kokota makambo",
    requiredField: "Esika oyo esengeli",
    // Table Headers
    name: "Kombo",
    status: "Statut",
    createdAt: "Esalemaki na",
    updatedAt: "Ebongisami na",
  }
};

type LanguageContextType = {
  currentLanguage: Language;
  changeLanguage: (lang: Language) => void;
  languages: Language[];
  t: (key: string) => string; // Translation function
};

const defaultLanguages: Language[] = [
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'ln', name: 'Lingala', flag: '🇨🇬' },
];

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Try to get the stored language from localStorage, or default to French
  const getStoredLanguage = (): Language => {
    if (typeof window !== 'undefined') {
      const storedLang = localStorage.getItem('preferredLanguage');
      if (storedLang) {
        try {
          const parsed = JSON.parse(storedLang);
          // Validate the parsed object has the right structure
          if (parsed && parsed.code && parsed.name && parsed.flag) {
            return parsed;
          }
        } catch (e) {
          console.error('Failed to parse stored language', e);
        }
      }
    }
    return defaultLanguages[0]; // Default to French
  };

  const [currentLanguage, setCurrentLanguage] = useState<Language>(getStoredLanguage);

  // Translation function
  const t = (key: string): string => {
    const langTranslations = translations[currentLanguage.code];
    return langTranslations && langTranslations[key] ? langTranslations[key] : key;
  };

  // Function to change the language
  const changeLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('preferredLanguage', JSON.stringify(lang));
      document.documentElement.lang = lang.code; // Update the HTML lang attribute
    }
  };

  // Set the initial language on first load
  useEffect(() => {
    if (typeof window !== 'undefined') {
      document.documentElement.lang = currentLanguage.code;
    }
  }, [currentLanguage.code]);

  // Listen for system settings language change event
  useEffect(() => {
    const handleSystemLanguageChange = (event: CustomEvent<{ languageCode: string }>) => {
      const langCode = event.detail?.languageCode;
      if (langCode) {
        const matchedLang = defaultLanguages.find(l => l.code === langCode);
        if (matchedLang && matchedLang.code !== currentLanguage.code) {
          changeLanguage(matchedLang);
        }
      }
    };
    
    window.addEventListener('systemSettingsLanguageChanged', handleSystemLanguageChange as EventListener);
    return () => window.removeEventListener('systemSettingsLanguageChanged', handleSystemLanguageChange as EventListener);
  }, [currentLanguage.code]);

  return (
    <LanguageContext.Provider value={{ currentLanguage, changeLanguage, languages: defaultLanguages, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
