import { Settings2, Users, ShoppingCart, Receipt, RotateCcw, Calculator, FileText, Landmark, BarChart3, Bell, Printer, ClipboardList } from 'lucide-react';
import type { GuideArticle, GuideModule } from '../types';

type ArticleSeed = {
  id: string;
  title: string;
  objective: string;
  location: string;
  intro: string;
  steps: string[];
  callouts?: string[];
  bestPractices: string[];
  faq: string[];
  related: string[];
  keywords: string[];
};

const makeArticle = (seed: ArticleSeed): GuideArticle => ({
  id: seed.id,
  title: seed.title,
  objective: seed.objective,
  location: seed.location,
  audience: ['Caissiers', 'Pharmaciens', 'Responsables de caisse', 'Comptables', 'Administrateurs'],
  intro: seed.intro,
  steps: seed.steps.map((title) => ({ title })),
  callouts: seed.callouts?.map((text, index) => ({ type: index === 0 ? 'info' : 'warning', text })) ?? [],
  bestPractices: seed.bestPractices,
  faq: seed.faq.map((item) => {
    const [q, a] = item.split('|');
    return { q, a };
  }),
  related: seed.related,
  keywords: seed.keywords,
});

export const ventesModule: GuideModule = {
  id: 'ventes',
  title: 'Ventes',
  tagline: 'Maîtriser le point de vente, les caisses, encaissements, factures, crédits, promotions et retours.',
  description: 'Le module Ventes couvre le pilotage commercial, les sessions de caisse, le POS, l’encaissement, la facturation, les crédits clients, les promotions, les dépenses et la configuration.',
  icon: ShoppingCart,
  accent: 'primary',
  sections: [
    {
      id: 'ventes-pilotage',
      title: 'Pilotage des ventes',
      icon: BarChart3,
      articles: [
      {"id": "ventes-dashboard-vue-ensemble", "title": "Comprendre le tableau de bord Ventes", "objective": "Interpréter les indicateurs clés du module Ventes.", "location": "Ventes", "intro": "CA journalier, transactions, panier moyen, objectif mensuel et évolution.", "steps": ["Ouvrir le module Ventes.", "Lire les cartes de synthèse.", "Comparer les tendances avec la période précédente.", "Accéder aux actions utiles depuis le dashboard."], "callouts": ["Les métriques sont filtrées par pharmacie/tenant.", "L’affichage dépend des permissions de vente."], "bestPractices": ["Contrôler les indicateurs en début et fin de journée.", "Croiser les variations importantes avec l’historique des transactions."], "faq": ["Pourquoi certains chiffres sont-ils masqués ?|Les permissions et l’isolation tenant limitent les données visibles."], "related": ["ventes-dashboard-caisses", "ventes-dashboard-transactions-recentes", "ventes-analytics-vue-ensemble"], "keywords": ["dashboard", "ventes", "ca", "panier", "tenant"]},
      {"id": "ventes-dashboard-caisses", "title": "Lire l’état des caisses depuis le dashboard", "objective": "Surveiller les caisses et sessions visibles depuis le pilotage.", "location": "Ventes", "intro": "L’état des caisses permet d’identifier les sessions ouvertes, fermées ou non configurées.", "steps": ["Consulter la zone des caisses.", "Vérifier la session active et le caissier associé.", "Contrôler le montant courant et la dernière transaction.", "Ouvrir la gestion des caisses si une alerte apparaît."], "callouts": ["Une caisse non configurée bloque certains flux d’encaissement."], "bestPractices": ["Créer les caisses avant le démarrage opérationnel.", "Associer clairement chaque session à un agent."], "faq": ["Une vente peut-elle être faite sans caisse ?|Seulement selon la configuration du mode Vente/Caisse séparé."], "related": ["ventes-caisses-vue-ensemble", "ventes-caisses-ouverture-session"], "keywords": ["caisse", "session", "dashboard", "caissier"]},
      {"id": "ventes-dashboard-actions-rapides", "title": "Utiliser les actions rapides des ventes", "objective": "Accéder rapidement aux opérations fréquentes.", "location": "Ventes", "intro": "Les actions rapides orientent vers nouvelle vente, encaissement, retour ou rapports.", "steps": ["Choisir l’action adaptée.", "Vérifier les droits disponibles.", "Poursuivre le flux dans le sous-module ouvert.", "Revenir au dashboard si nécessaire."], "callouts": ["La navigation doit rester interne au Dashboard via le contexte de navigation.", "Ces actions sont utiles pendant les heures de forte affluence."], "bestPractices": ["Former les caissiers aux raccourcis.", "Limiter les actions sensibles aux profils habilités."], "faq": ["Pourquoi une action manque-t-elle ?|Elle peut être masquée par les permissions."], "related": ["ventes-point-de-vente", "ventes-encaissements-vue-ensemble", "ventes-retours"], "keywords": ["actions", "rapides", "navigation", "vente"]},
      {"id": "ventes-dashboard-transactions-recentes", "title": "Consulter les transactions récentes", "objective": "Retrouver rapidement les dernières ventes.", "location": "Ventes", "intro": "La liste récente donne accès aux détails, reçus, annulations et modes de paiement.", "steps": ["Lire les ventes récentes.", "Ouvrir le détail d’une transaction.", "Réimprimer le reçu si nécessaire.", "Annuler uniquement après contrôle."], "callouts": ["Une annulation influence les rapports de ventes et le suivi caisse.", "Les reçus respectent la configuration d’impression du tenant."], "bestPractices": ["Vérifier le client et le mode de paiement avant annulation.", "Documenter toute correction."], "faq": ["Puis-je réimprimer un reçu ?|Oui si la transaction est accessible et autorisée."], "related": ["ventes-historique-details", "ventes-configuration-impression"], "keywords": ["transactions", "reçu", "annulation", "historique"]}
    ].map(makeArticle),
    },
    {
      id: 'ventes-caisses',
      title: 'Caisses et sessions',
      icon: Landmark,
      articles: [
      {"id": "ventes-caisses-vue-ensemble", "title": "Comprendre la gestion des caisses", "objective": "Piloter les caisses, sessions et soldes.", "location": "Ventes → Caisses", "intro": "La gestion des caisses centralise sessions actives, soldes, mouvements et alertes.", "steps": ["Ouvrir Ventes → Caisses.", "Contrôler les sessions actives.", "Vérifier le solde courant.", "Traiter les alertes avant encaissement."], "callouts": ["Une session ouverte est requise pour les flux non séparés."], "bestPractices": ["Ouvrir une session par période.", "Clôturer chaque session avec rapprochement."], "faq": ["Pourquoi aucune caisse n’apparaît ?|Les caisses doivent être configurées et accessibles par permissions."], "related": ["ventes-caisses-ouverture-session", "ventes-caisses-fermeture-session"], "keywords": ["caisses", "sessions", "solde", "mouvements"]},
      {"id": "ventes-caisses-ouverture-session", "title": "Ouvrir une session de caisse", "objective": "Démarrer une session opérationnelle de caisse.", "location": "Ventes → Caisses → Sessions", "intro": "L’ouverture définit la caisse, le type de session et le fonds initial.", "steps": ["Choisir la caisse.", "Sélectionner Matin, Midi ou Soir.", "Saisir le fonds de caisse.", "Valider l’agent ou caissier."], "callouts": ["Une vente en mode non séparé nécessite une session ouverte.", "Ouvrir une session par période facilite le rapprochement."], "bestPractices": ["Saisir un fonds exact.", "Éviter de partager une session entre plusieurs agents sans procédure."], "faq": ["Puis-je ouvrir plusieurs sessions ?|Oui selon les caisses et règles internes."], "related": ["ventes-caisses-fermeture-session", "ventes-pos-mode-separe-encaissement"], "keywords": ["ouverture", "session", "caisse", "fonds"]},
      {"id": "ventes-caisses-fermeture-session", "title": "Fermer une session de caisse", "objective": "Clôturer une session avec contrôle des écarts.", "location": "Ventes → Caisses → Historique / Fermeture", "intro": "La fermeture rapproche montant théorique, montant réel, ventes, bons non encaissés, marge et marque.", "steps": ["Sélectionner la session ouverte.", "Contrôler le montant théorique.", "Saisir le montant réel.", "Analyser les écarts puis clôturer."], "callouts": ["Les métriques de clôture sont persistées dans sessions_caisse.", "Vérifier les écarts avant validation définitive."], "bestPractices": ["Imprimer ou exporter le rapport de session.", "Justifier tout écart de caisse."], "faq": ["Que faire en cas d’écart ?|Identifier les mouvements, bons non encaissés et paiements avant clôture."], "related": ["ventes-caisses-rapports-session", "ventes-caisses-mouvements"], "keywords": ["fermeture", "clôture", "écart", "marge", "marque"]},
      {"id": "ventes-caisses-gestion-caisses", "title": "Gérer les caisses disponibles", "objective": "Administrer les points de caisse utilisables.", "location": "Ventes → Caisses → Caisses", "intro": "La gestion des caisses couvre création, modification, statut et association aux sessions.", "steps": ["Consulter la liste des caisses.", "Créer ou modifier une caisse.", "Définir le statut.", "Associer les sessions opérationnelles."], "callouts": ["Désactiver une caisse inutilisée évite les erreurs d’affectation."], "bestPractices": ["Nommer les caisses selon leur emplacement réel.", "Vérifier les droits avant modification."], "faq": ["Une caisse supprimée conserve-t-elle l’historique ?|L’historique doit rester consultable selon les règles d’audit."], "related": ["ventes-configuration-caisses", "ventes-caisses-historique-sessions"], "keywords": ["gestion", "caisses", "statut", "point de vente"]},
      {"id": "ventes-caisses-historique-sessions", "title": "Consulter l’historique des sessions", "objective": "Retrouver les sessions passées et leurs soldes.", "location": "Ventes → Caisses → Historique", "intro": "L’historique permet filtrage, pagination, consultation par caissier, caisse, date et statut.", "steps": ["Choisir les filtres.", "Consulter les sessions.", "Ouvrir une session pour le détail.", "Exporter Excel ou PDF si nécessaire."], "callouts": ["L’export doit refléter les filtres appliqués."], "bestPractices": ["Limiter les exports aux périodes utiles.", "Contrôler le statut avant analyse financière."], "faq": ["Puis-je filtrer par caissier ?|Oui si les données sont disponibles et autorisées."], "related": ["ventes-caisses-rapports-session"], "keywords": ["historique", "sessions", "export", "caissier"]},
      {"id": "ventes-caisses-rapports-session", "title": "Exploiter les rapports de session", "objective": "Analyser les ventes, encaissements et mouvements d’une session.", "location": "Ventes → Caisses → Rapports", "intro": "Les rapports de session facilitent le rapprochement de caisse et les contrôles internes.", "steps": ["Sélectionner la session.", "Lire ventes, encaissements et bons non encaissés.", "Contrôler les mouvements.", "Imprimer ou exporter."], "callouts": ["Les rapports servent de support de clôture."], "bestPractices": ["Archiver les rapports importants.", "Comparer avec les états d’encaissement."], "faq": ["Le rapport inclut-il les bons non encaissés ?|Oui lorsque le flux Vente/Caisse séparé est utilisé."], "related": ["ventes-encaissements-rapports", "ventes-caisses-fermeture-session"], "keywords": ["rapport", "session", "encaissements", "bons"]},
      {"id": "ventes-caisses-mouvements", "title": "Enregistrer les mouvements de caisse", "objective": "Tracer les entrées et sorties hors ventes.", "location": "Ventes → Caisses", "intro": "Les mouvements corrigent le solde de caisse avec motif, montant et justification.", "steps": ["Choisir entrée ou sortie.", "Saisir le montant.", "Indiquer un motif clair.", "Valider le mouvement."], "callouts": ["Un mouvement de caisse doit toujours être justifié.", "Les mouvements contribuent au rapprochement de fermeture."], "bestPractices": ["Éviter les libellés vagues.", "Contrôler l’impact sur le solde avant validation."], "faq": ["Peut-on annuler un mouvement ?|Selon les permissions et la politique d’audit."], "related": ["ventes-depenses-vue-ensemble", "ventes-caisses-fermeture-session"], "keywords": ["mouvements", "entrée", "sortie", "justification"]}
    ].map(makeArticle),
    },
    {
      id: 'ventes-pos',
      title: 'Point de vente',
      icon: ShoppingCart,
      articles: [
      {"id": "ventes-point-de-vente", "title": "Réaliser une vente au Point de Vente", "objective": "Effectuer une vente complète au POS.", "location": "Ventes → Point de Vente → Vente", "intro": "Recherche produit, scan, panier, client, assurance, paiement simple et impression.", "steps": ["Rechercher ou scanner un produit.", "Ajouter les lignes au panier.", "Sélectionner client, assurance ou remise.", "Encaisser puis imprimer le reçu."], "callouts": ["Le POS utilise les lots comme source de vérité pour les prix et le stock.", "Le stock insuffisant bloque l’ajout au panier."], "bestPractices": ["Scanner les produits quand possible.", "Vérifier la couverture assurance avant paiement."], "faq": ["Puis-je fractionner une unité ?|Oui pour les produits configurés avec un niveau de détail compatible."], "related": ["ventes-pos-client", "ventes-pos-assurance", "ventes-pos-paiement-simple", "ventes-dashboard-transactions-recentes"], "keywords": ["pos", "vente", "panier", "paiement", "reçu"]},
      {"id": "ventes-pos-scanner-code-barres", "title": "Utiliser le lecteur de codes-barres", "objective": "Accélérer l’ajout produit via douchette.", "location": "Ventes → Point de Vente", "intro": "Scan physique, recherche par code-barres, ajout automatique et produit introuvable.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Scanner les produits réduit les erreurs de saisie.", "Le POS est optimisé pour les lecteurs physiques rapides."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-recherche-produits"], "keywords": ["scanner", "code-barres", "douchette", "pos"]},
      {"id": "ventes-pos-recherche-produits", "title": "Rechercher les produits au POS", "objective": "Trouver les produits vendables avec disponibilité.", "location": "Ventes → Point de Vente → Recherche produits", "intro": "Recherche serveur, pagination, lots valides, expiration, prix TTC et stock.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Les lots expirés ou invalides ne doivent pas être utilisés pour la vente.", "Vérifier le lot pour les produits sensibles."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-selection-lots"], "keywords": ["recherche", "produits", "lots", "stock"]},
      {"id": "ventes-pos-selection-lots", "title": "Sélectionner les lots de vente", "objective": "Choisir le lot approprié pour la sortie de stock.", "location": "Ventes → Point de Vente → Sélection lot", "intro": "Numéro de lot, quantité disponible, péremption, prix et traçabilité FIFO/FEFO.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["stock-lots-suivi", "ventes-pos-recherche-produits"], "keywords": ["lots", "fifo", "fefo", "traçabilité"]},
      {"id": "ventes-pos-panier", "title": "Gérer le panier de vente", "objective": "Modifier les lignes avant paiement.", "location": "Ventes → Point de Vente → Panier", "intro": "Quantités, suppression, vidage panier, prix unitaire, total ligne et nombre d’articles.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-modification-prix", "ventes-pos-paiement-simple"], "keywords": ["panier", "quantité", "prix", "total"]},
      {"id": "ventes-pos-modification-prix", "title": "Modifier un prix à la vente", "objective": "Encadrer les changements de prix au POS.", "location": "Ventes → Point de Vente → Panier", "intro": "Option allowPriceEditAtSale, dialogue de prix, validation, droits et totaux.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["La modification de prix doit rester contrôlée par permission et configuration.", "Les montants FCFA respectent les règles d’arrondi du projet."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-configuration-generale"], "keywords": ["prix", "remise", "permission", "fcfa"]},
      {"id": "ventes-pos-client", "title": "Sélectionner le client au POS", "objective": "Associer la vente au bon client.", "location": "Ventes → Point de Vente → Client", "intro": "Client ordinaire, conventionné, entreprise, personnel, coordonnées, remise et crédit.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-assurance", "ventes-credit-comptes"], "keywords": ["client", "conventionné", "remise", "crédit"]},
      {"id": "ventes-pos-assurance", "title": "Appliquer une couverture assurance", "objective": "Calculer les parts client et assureur.", "location": "Ventes → Point de Vente → Client / Assurance", "intro": "Assureur, numéro assurance, taux de couverture, part assurance, part client, Agent/Ayant Droit.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Les taux Agent et Ayant Droit recalculent instantanément les parts patient/assureur.", "Vérifier la couverture avant validation."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-ticket-moderateur"], "keywords": ["assurance", "agent", "ayant droit", "couverture"]},
      {"id": "ventes-pos-ticket-moderateur", "title": "Comprendre le ticket modérateur et les remises", "objective": "Lire correctement les montants à payer.", "location": "Ventes → Point de Vente → Totaux", "intro": "Remise automatique, ticket modérateur, part client, part assurance et total final.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-assurance", "ventes-pos-paiement-simple"], "keywords": ["ticket modérateur", "remise", "totaux"]},
      {"id": "ventes-pos-paiement-simple", "title": "Encaisser une vente en paiement simple", "objective": "Finaliser une vente avec un seul moyen de paiement.", "location": "Ventes → Point de Vente → Paiement simple", "intro": "Espèces, carte, mobile money, assurance, montant reçu, rendu monnaie et référence.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-paiement-fractionne", "ventes-configuration-paiement"], "keywords": ["paiement", "espèces", "carte", "mobile money"]},
      {"id": "ventes-pos-paiement-fractionne", "title": "Encaisser une vente en paiement fractionné", "objective": "Répartir un total sur plusieurs moyens de paiement.", "location": "Ventes → Point de Vente → Paiement fractionné", "intro": "Répartition, validation des montants, solde restant et finalisation.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-paiement-simple"], "keywords": ["paiement fractionné", "solde", "encaissement"]},
      {"id": "ventes-pos-mode-separe-vente", "title": "Utiliser le mode Vente seule", "objective": "Créer une vente sans encaissement immédiat.", "location": "Ventes → Point de Vente → Vente seule", "intro": "Séparation Vente/Caisse, session ouverte, ticket de vente et transaction en attente.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Le mode séparé est activé dans Configuration Ventes → Général.", "La vente seule ne remplace pas l’encaissement."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-mode-separe-encaissement", "ventes-caisses-ouverture-session"], "keywords": ["vente seule", "séparation", "caisse"]},
      {"id": "ventes-pos-mode-separe-encaissement", "title": "Encaisser les ventes en attente", "objective": "Régler les ventes créées en mode séparé.", "location": "Ventes → Point de Vente → Encaissement", "intro": "Ventes en attente, session, recherche numéro, paiement, caissier assigné et reçu.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Seuls les profils autorisés ou le caissier assigné peuvent encaisser.", "Les transactions retournées ou orphelines sont filtrées pour éviter les blocages."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-mode-separe-vente", "ventes-caisses-fermeture-session"], "keywords": ["encaissement", "vente attente", "caissier"]},
      {"id": "ventes-pos-proforma", "title": "Créer une facture proforma depuis le POS", "objective": "Émettre une proforma sans sortie immédiate de stock.", "location": "Ventes → Point de Vente → Proforma", "intro": "Catalogue global, panier, client optionnel, validité, notes, PDF et liste.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Une proforma utilise le catalogue global sans déduction immédiate du stock.", "La sortie de stock intervient uniquement lors de la conversion en vente réelle."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-proformas-liste", "ventes-facturation-creer", "ventes-point-de-vente"], "keywords": ["proforma", "devis", "pdf", "catalogue"]},
      {"id": "ventes-pos-proformas-liste", "title": "Consulter les proformas existantes", "objective": "Retrouver les proformas et leur statut.", "location": "Ventes → Point de Vente → Proforma → Voir les proformas", "intro": "Liste, statut, client, montant, conversion, impression et consultation.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-proforma"], "keywords": ["proformas", "liste", "conversion"]},
      {"id": "ventes-pos-ordonnance", "title": "Associer une ordonnance à une vente", "objective": "Relier les informations d’ordonnance à la transaction.", "location": "Ventes → Point de Vente → Ordonnance", "intro": "Patient, références ordonnance, produits prescrits et lien avec la vente.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["ordonnance", "patient", "prescription"]},
      {"id": "ventes-pos-produit-demande", "title": "Enregistrer un produit demandé", "objective": "Tracer une demande client pour produit absent.", "location": "Ventes → Point de Vente → Produit demandé", "intro": "Produit introuvable, quantité souhaitée, commentaire et exploitation stock/approvisionnement.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["stock-approvisionnement-commandes"], "keywords": ["produit demandé", "rupture", "demande"]},
      {"id": "ventes-pos-mise-en-detail", "title": "Fractionner une unité de vente", "objective": "Convertir une unité source vers un niveau de détail.", "location": "Ventes → Point de Vente → Mise en détail", "intro": "Boîte, plaquette, unité, décrément source, incrément détail et cache stock.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Le fractionnement modifie le stock en temps réel.", "L’action dépend de la configuration du produit."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["stock-mouvements-journal"], "keywords": ["mise en détail", "fractionnement", "stock"]},
      {"id": "ventes-pos-fidelite", "title": "Utiliser la fidélité au POS", "objective": "Appliquer les avantages fidélité pendant la vente.", "location": "Ventes → Point de Vente → Fidélité", "intro": "Points, récompense, points gagnés, remise fidélité et historique client.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-fidelite-membres", "ventes-fidelite-recompenses"], "keywords": ["fidélité", "points", "récompense"]},
      {"id": "ventes-pos-analytiques", "title": "Lire les analytiques intégrées du POS", "objective": "Consulter les indicateurs rapides du POS.", "location": "Ventes → Point de Vente → Analytiques", "intro": "Ventes POS, performance, panier moyen, modes de paiement et tendances.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-analytics-vue-ensemble"], "keywords": ["analytiques", "pos", "performance"]}
    ].map(makeArticle),
    },
    {
      id: 'ventes-encaissements',
      title: 'Encaissements',
      icon: Receipt,
      articles: [
      {"id": "ventes-encaissements-vue-ensemble", "title": "Comprendre le dashboard Encaissements", "objective": "Suivre les montants encaissés par période.", "location": "Ventes → Encaissements", "intro": "Total jour, semaine, mois, panier moyen et comparaison avec hier.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["encaissements", "dashboard", "panier"]},
      {"id": "ventes-encaissements-transactions", "title": "Consulter les transactions encaissées", "objective": "Rechercher les encaissements validés.", "location": "Ventes → Encaissements → Transactions", "intro": "Recherche, filtres, pagination, paiement, statut, détail et exports CSV/Excel/PDF.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-historique-details"], "keywords": ["transactions", "encaissement", "export"]},
      {"id": "ventes-encaissements-resume", "title": "Lire le résumé des encaissements", "objective": "Comprendre la ventilation des encaissements.", "location": "Ventes → Encaissements → Résumé", "intro": "Répartition par paiement, évolution des ventes, synthèse de période et tendances.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["résumé", "paiements", "tendances"]},
      {"id": "ventes-encaissements-rapports", "title": "Générer les rapports d’encaissement", "objective": "Produire les états d’encaissement utiles au suivi.", "location": "Ventes → Encaissements → Rapports", "intro": "Rapports journalier, hebdomadaire, mensuel, fiscal et export.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Les montants respectent la devise et les paramètres régionaux du tenant.", "Les rapports fiscaux doivent rester cohérents avec Comptabilité/SYSCOHADA."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-caisses-rapports-session"], "keywords": ["rapport", "fiscal", "export"]}
    ].map(makeArticle),
    },
    {
      id: 'ventes-historique',
      title: 'Historique des transactions',
      icon: ClipboardList,
      articles: [
      {"id": "ventes-historique-liste", "title": "Consulter la liste des transactions", "objective": "Retrouver toutes les transactions de vente.", "location": "Ventes → Historique → Liste", "intro": "Recherche, filtres avancés, tri, pagination, détail, annulation et exports.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-historique-filtres", "ventes-historique-details"], "keywords": ["historique", "transactions", "liste"]},
      {"id": "ventes-historique-filtres", "title": "Filtrer l’historique des ventes", "objective": "Limiter l’historique aux données pertinentes.", "location": "Ventes → Historique → Liste → Filtres", "intro": "Période, paiement, statut, caissier, caisse, montant min/max et recherche texte.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-historique-liste"], "keywords": ["filtres", "période", "statut"]},
      {"id": "ventes-historique-details", "title": "Lire le détail d’une transaction", "objective": "Analyser une vente ligne par ligne.", "location": "Ventes → Historique → Liste → Détails", "intro": "Lignes, client, agent, caisse, paiement, taxes, remises et statut.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-retours", "ventes-dashboard-transactions-recentes"], "keywords": ["détails", "lignes", "transaction"]},
      {"id": "ventes-historique-analyses", "title": "Analyser l’historique des ventes", "objective": "Exploiter les tendances issues de l’historique.", "location": "Ventes → Historique → Analyses", "intro": "Évolution, méthodes de paiement, performance caissier, caisse et distribution horaire.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-analytics-vue-ensemble"], "keywords": ["analyses", "historique", "performance"]},
      {"id": "ventes-historique-timeline", "title": "Suivre la timeline des transactions", "objective": "Visualiser les événements de vente dans le temps.", "location": "Ventes → Historique → Timeline", "intro": "Chronologie, événements, ventes récentes, consultation rapide et anomalies.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["timeline", "chronologie", "anomalies"]},
      {"id": "ventes-historique-rapports", "title": "Exporter les rapports d’historique", "objective": "Générer des exports managériaux ou comptables.", "location": "Ventes → Historique → Rapports", "intro": "PDF, Excel, période, filtres appliqués et usage comptable/managérial.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-encaissements-rapports"], "keywords": ["rapports", "pdf", "excel"]}
    ].map(makeArticle),
    },
    {
      id: 'ventes-retours-echanges',
      title: 'Retours et échanges',
      icon: RotateCcw,
      articles: [
      {"id": "ventes-retours", "title": "Traiter les retours et avoirs", "objective": "Gérer un retour client avec piste d’audit.", "location": "Ventes → Retours", "intro": "Transaction origine, articles, quantité retournée, état produit, remboursement, motif et validation.", "steps": ["Rechercher la transaction d’origine.", "Sélectionner les lignes retournées.", "Indiquer état, quantité et motif.", "Valider le traitement selon le statut."], "callouts": ["Un retour validé influence stock, caisse, rapports et comptabilité.", "Le traitement final est atomique via la logique de retour centralisée."], "bestPractices": ["Documenter précisément le motif.", "Éviter les retours sans transaction d’origine."], "faq": ["Un retour remet-il automatiquement le stock à jour ?|Oui lorsque le flux validé prévoit la remise en stock."], "related": ["ventes-retours-attente", "ventes-retours-traitement", "ventes-historique-details"], "keywords": ["retour", "avoir", "remboursement", "stock"]},
      {"id": "ventes-retours-nouveau", "title": "Créer une demande de retour", "objective": "Initier un retour à partir d’une vente.", "location": "Ventes → Retours → Nouveau Retour", "intro": "Numéro transaction, recherche, sélection lignes, raison globale, motif par article et notes.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-retours-attente"], "keywords": ["nouveau retour", "demande", "motif"]},
      {"id": "ventes-retours-attente", "title": "Valider ou rejeter les retours en attente", "objective": "Contrôler les demandes avant traitement final.", "location": "Ventes → Retours → Retours en Attente", "intro": "Liste, statut, approbation, rejet, notes et contrôle responsable.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-retours-traitement"], "keywords": ["retours attente", "validation", "rejet"]},
      {"id": "ventes-retours-traitement", "title": "Finaliser le traitement d’un retour", "objective": "Clôturer un retour approuvé.", "location": "Ventes → Retours → Traitement", "intro": "Remboursement, remise en stock ou non, impact financier et clôture.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Les retours intégraux peuvent supprimer la transaction d’origine après détachement sécurisé des liens.", "Les transactions sans lignes sont filtrées pour préserver les clôtures de caisse."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-retours-historique"], "keywords": ["traitement", "remboursement", "atomique"]},
      {"id": "ventes-retours-historique", "title": "Consulter l’historique des retours", "objective": "Suivre les retours traités ou rejetés.", "location": "Ventes → Retours → Historique", "intro": "Filtres, statut, client, transaction origine, montant et export Excel/PDF.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["historique retours", "export", "statut"]}
    ].map(makeArticle),
    },
    {
      id: 'ventes-facturation',
      title: 'Facturation client',
      icon: FileText,
      articles: [
      {"id": "ventes-facturation-vue-ensemble", "title": "Comprendre la facturation client", "objective": "Piloter les factures client et leurs statuts.", "location": "Ventes → Facturation", "intro": "Statistiques, brouillons, émises, payées, en retard et montants.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["facturation", "factures", "statuts"]},
      {"id": "ventes-facturation-creer", "title": "Créer une facture client", "objective": "Émettre une facture client depuis le catalogue.", "location": "Ventes → Facturation → Nouvelle facture", "intro": "Client, lignes, produits du catalogue, quantités, taxes, total et enregistrement.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["La facturation peut utiliser le catalogue global même hors stock.", "Garder la cohérence avec le module Comptabilité."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-facturation-paiement", "comptabilite-facturation"], "keywords": ["facture", "client", "catalogue"]},
      {"id": "ventes-facturation-rechercher-filtrer", "title": "Rechercher et filtrer les factures", "objective": "Retrouver rapidement les factures utiles.", "location": "Ventes → Facturation", "intro": "Recherche numéro, client, libellé, statut, factures en retard et suivi paiement.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["recherche", "factures", "retard"]},
      {"id": "ventes-facturation-statut", "title": "Modifier le statut d’une facture", "objective": "Faire évoluer une facture dans son cycle de vie.", "location": "Ventes → Facturation → Statut", "intro": "Brouillon, émise, payée, en retard, annulée et envoi.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-facturation-paiement"], "keywords": ["statut", "brouillon", "payée"]},
      {"id": "ventes-facturation-paiement", "title": "Enregistrer un paiement de facture", "objective": "Saisir le règlement d’une facture client.", "location": "Ventes → Facturation → Paiement", "intro": "Facture, montant, date, mode, référence et statut paiement.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-encaissements-transactions"], "keywords": ["paiement", "facture", "règlement"]},
      {"id": "ventes-facturation-relance", "title": "Envoyer une relance de facture", "objective": "Suivre les factures en retard.", "location": "Ventes → Facturation → Relance", "intro": "Facture en retard, date de relance, message, suivi et historique.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-facturation-rechercher-filtrer"], "keywords": ["relance", "retard", "facture"]},
      {"id": "ventes-facturation-impression-export", "title": "Imprimer et exporter les factures", "objective": "Produire les documents facture en PDF ou impression.", "location": "Ventes → Facturation", "intro": "Génération PDF, impression, téléchargement, lignes et paramètres régionaux.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["La génération PDF suit le standard jsPDF du projet.", "Les factures doivent rester alignées avec le module Comptabilité."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-configuration-impression"], "keywords": ["impression", "pdf", "export"]}
    ].map(makeArticle),
    },
    {
      id: 'ventes-analytics',
      title: 'Analytics ventes',
      icon: BarChart3,
      articles: [
      {"id": "ventes-analytics-vue-ensemble", "title": "Comprendre Analytics & Statistiques", "objective": "Lire les indicateurs avancés des ventes.", "location": "Ventes → Analytics", "intro": "Période jour/semaine/mois/année/personnalisée, filtres, KPI, actualisation et exports.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-analytics-revenus", "ventes-analytics-produits"], "keywords": ["analytics", "statistiques", "kpi"]},
      {"id": "ventes-analytics-revenus", "title": "Analyser les revenus", "objective": "Suivre le chiffre d’affaires dans le temps.", "location": "Ventes → Analytics → Revenus", "intro": "Évolution CA, performance hebdomadaire, tendance et comparaison par période.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["revenus", "ca", "tendance"]},
      {"id": "ventes-analytics-transactions", "title": "Analyser les transactions", "objective": "Comprendre le volume et la fréquence des ventes.", "location": "Ventes → Analytics → Transactions", "intro": "Nombre de transactions, panier moyen, évolution, fréquence et variations.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["transactions", "panier moyen", "fréquence"]},
      {"id": "ventes-analytics-produits", "title": "Identifier les meilleurs produits vendus", "objective": "Repérer les produits qui génèrent le plus de ventes.", "location": "Ventes → Analytics → Produits", "intro": "Top produits, CA, quantité, marge et catégories.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Les produits doivent être référencés avec libelle_produit.", "Croiser ces données avec Stock → Analyse ABC."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["stock-analyses-abc"], "keywords": ["produits", "libelle_produit", "marge"]},
      {"id": "ventes-analytics-paiements", "title": "Analyser les modes de paiement", "objective": "Comprendre la répartition des moyens de paiement.", "location": "Ventes → Analytics → Paiements", "intro": "Espèces, carte, mobile money, assurance, distribution et tendance.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["paiements", "espèces", "assurance"]},
      {"id": "ventes-analytics-performance", "title": "Suivre la performance du personnel", "objective": "Comparer l’activité commerciale des agents.", "location": "Ventes → Analytics → Performance", "intro": "Ventes par agent, nombre transactions, panier moyen, performance relative et équipe.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["personnel", "performance", "agent"]},
      {"id": "ventes-analytics-insights", "title": "Exploiter les insights de vente", "objective": "Identifier alertes, opportunités et variations.", "location": "Ventes → Analytics", "intro": "Alertes de performance, opportunités, variations anormales, recommandations et lecture managériale.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["insights", "alertes", "recommandations"]}
    ].map(makeArticle),
    },
    {
      id: 'ventes-credit',
      title: 'Crédit client',
      icon: Calculator,
      articles: [
      {"id": "ventes-credit-vue-ensemble", "title": "Comprendre la gestion du crédit client", "objective": "Piloter les encours et paiements crédit.", "location": "Ventes → Crédit", "intro": "Comptes crédit, encours, échéanciers, alertes, rapports et paiements.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-credit-comptes"], "keywords": ["crédit", "encours", "échéancier"]},
      {"id": "ventes-credit-comptes", "title": "Gérer les comptes crédit", "objective": "Créer et contrôler les comptes crédit client.", "location": "Ventes → Crédit → Comptes Crédit", "intro": "Recherche, statut, nouveau compte, limite, suspension, ajustement et paiement.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Une limite crédit mal configurée peut exposer la pharmacie à un risque financier.", "Le crédit est lié au suivi client et aux bons non encaissés."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-credit-echeanciers", "ventes-credit-alertes", "ventes-caisses-fermeture-session"], "keywords": ["comptes crédit", "limite", "suspension"]},
      {"id": "ventes-credit-paiement", "title": "Enregistrer un paiement crédit", "objective": "Réduire l’encours d’un compte crédit.", "location": "Ventes → Crédit → Enregistrer Paiement", "intro": "Compte, montant, référence, date, solde restant et validation.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-credit-historique"], "keywords": ["paiement crédit", "solde", "référence"]},
      {"id": "ventes-credit-historique", "title": "Consulter l’historique crédit", "objective": "Auditer les opérations de crédit.", "location": "Ventes → Crédit → Historique", "intro": "Transactions crédit, paiements, ajustements, suspension et audit.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["historique crédit", "audit", "ajustement"]},
      {"id": "ventes-credit-echeanciers", "title": "Suivre les échéanciers de paiement", "objective": "Surveiller les paiements à venir et retards.", "location": "Ventes → Crédit → Échéanciers", "intro": "Échéances, retards, dates, statut et priorisation.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-credit-alertes"], "keywords": ["échéanciers", "retards", "dates"]},
      {"id": "ventes-credit-alertes", "title": "Traiter les alertes crédit", "objective": "Réagir aux risques de crédit.", "location": "Ventes → Crédit → Alertes", "intro": "Paiements en retard, dépassement limite, relances et suspension éventuelle.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-credit-rapports"], "keywords": ["alertes crédit", "relance", "limite"]},
      {"id": "ventes-credit-rapports", "title": "Exploiter les rapports crédit", "objective": "Analyser l’exposition financière crédit.", "location": "Ventes → Crédit → Rapports", "intro": "Encours total, comptes à risque, remboursements, retards et export.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["rapports crédit", "encours", "export"]}
    ].map(makeArticle),
    },
    {
      id: 'ventes-promotions',
      title: 'Promotions et fidélité',
      icon: Users,
      articles: [
      {"id": "ventes-promotions-vue-ensemble", "title": "Comprendre Promotions & Fidélité", "objective": "Piloter promotions, fidélité et récompenses.", "location": "Ventes → Promotions", "intro": "Statistiques, promotions, programme fidélité, récompenses et analytics.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-promotions-gestion", "ventes-fidelite-membres"], "keywords": ["promotions", "fidélité", "récompenses"]},
      {"id": "ventes-promotions-gestion", "title": "Créer et gérer les promotions", "objective": "Administrer les offres promotionnelles.", "location": "Ventes → Promotions → Promotions", "intro": "Recherche, type, création, modification, activation, détail et limite d’utilisation.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Contrôler les dates et limites avant activation.", "Désactiver une promotion expirée évite les remises non souhaitées."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-promotions-types", "ventes-promotions-analytics"], "keywords": ["promotions", "activation", "remise"]},
      {"id": "ventes-promotions-types", "title": "Comprendre les types de promotions", "objective": "Choisir le bon mécanisme promotionnel.", "location": "Ventes → Promotions → Promotions", "intro": "Pourcentage, montant fixe, achetez/obtenez, quantité, valeur et période.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["types", "pourcentage", "montant fixe"]},
      {"id": "ventes-fidelite-membres", "title": "Gérer les membres du programme fidélité", "objective": "Suivre les clients membres et leurs niveaux.", "location": "Ventes → Promotions → Programme Fidélité", "intro": "Recherche membre, carte, Bronze/Silver/Gold/Platinum, points, dépenses et activité.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-fidelite", "ventes-fidelite-recompenses"], "keywords": ["membres", "bronze", "points"]},
      {"id": "ventes-fidelite-recompenses", "title": "Gérer les récompenses fidélité", "objective": "Configurer les avantages échangeables en points.", "location": "Ventes → Promotions → Récompenses", "intro": "Récompense, type remise/produit gratuit/cashback, coût, valeur, niveau requis et stock.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-fidelite-membres"], "keywords": ["récompenses", "cashback", "points"]},
      {"id": "ventes-promotions-analytics", "title": "Analyser les performances des promotions", "objective": "Mesurer l’efficacité des offres et du programme fidélité.", "location": "Ventes → Promotions → Analytics", "intro": "Période, utilisations, remises totales, membres, conversion, performance et niveaux.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["analytics promotions", "conversion", "remises"]}
    ].map(makeArticle),
    },
    {
      id: 'ventes-depenses',
      title: 'Dépenses de caisse',
      icon: Receipt,
      articles: [
      {"id": "ventes-depenses-vue-ensemble", "title": "Comprendre les dépenses de caisse", "objective": "Suivre les sorties de caisse hors ventes.", "location": "Ventes → Dépenses", "intro": "Dépenses depuis les caisses, liste, statistiques, actualisation et exports.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-depenses-liste"], "keywords": ["dépenses", "caisse", "sorties"]},
      {"id": "ventes-depenses-liste", "title": "Consulter et filtrer les dépenses de caisse", "objective": "Retrouver les dépenses avec filtres et exports.", "location": "Ventes → Dépenses → Liste des dépenses", "intro": "Filtres serveur, pagination, total, tri, export Excel/PDF, édition et annulation.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Une dépense annulée doit conserver un motif.", "Les permissions déterminent les actions possibles."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-depenses-modifier-annuler"], "keywords": ["liste dépenses", "filtres", "export"]},
      {"id": "ventes-depenses-modifier-annuler", "title": "Modifier ou annuler une dépense", "objective": "Corriger une dépense avec justification.", "location": "Ventes → Dépenses → Liste des dépenses", "intro": "Sélection, modification montant/description/motif, annulation, justification et rafraîchissement.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["modifier", "annuler", "justification"]},
      {"id": "ventes-depenses-statistiques", "title": "Analyser les dépenses de caisse", "objective": "Comprendre la répartition des sorties.", "location": "Ventes → Dépenses → Statistiques", "intro": "Statistiques globales, répartition par motif, graphiques catégories et suivi des sorties.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["statistiques", "motifs", "sorties"]}
    ].map(makeArticle),
    },
    {
      id: 'ventes-configuration',
      title: 'Configuration ventes',
      icon: Settings2,
      articles: [
      {"id": "ventes-configuration-generale", "title": "Configurer les paramètres généraux de vente", "objective": "Définir le comportement global du module Ventes.", "location": "Ventes → Configuration → Général", "intro": "Sauvegarde auto, scanner, affichage stock, client obligatoire, prix, remises, stock négatif et séparation Vente/Caisse.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Autoriser le stock négatif ou la modification de prix doit être réservé aux profils habilités.", "La séparation Vente/Caisse modifie les onglets visibles du POS."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-mode-separe-vente", "ventes-configuration-impression", "ventes-configuration-paiement"], "keywords": ["configuration", "général", "scanner", "stock négatif"]},
      {"id": "ventes-configuration-tva", "title": "Configurer la TVA et les taxes", "objective": "Paramétrer les calculs fiscaux de vente.", "location": "Ventes → Configuration → TVA", "intro": "Taxation, taux TVA, calculs, impact HT/TTC et cohérence fiscale.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["Les calculs de prix et taxes appliquent les règles d’arrondi FCFA.", "Vérifier la cohérence avec Comptabilité/SYSCOHADA."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": [], "keywords": ["tva", "taxes", "fcfa"]},
      {"id": "ventes-configuration-paiement", "title": "Configurer les moyens de paiement", "objective": "Choisir les moyens disponibles au paiement.", "location": "Ventes → Configuration → Paiement", "intro": "Espèces, carte, mobile money, assurance, références et activation/désactivation.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-pos-paiement-simple"], "keywords": ["paiement", "moyens", "activation"]},
      {"id": "ventes-configuration-impression", "title": "Configurer l’impression des reçus et tickets", "objective": "Adapter les reçus au tenant.", "location": "Ventes → Configuration → Impression", "intro": "Autoprint, logo, code-barres, format papier, en-tête, pied de page et message.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": ["L’impression suit la hiérarchie PharmaSoft : label système, informations tenant, puis texte personnalisé.", "Éviter les textes fictifs ou doublons dans les en-têtes/pieds."], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-facturation-impression-export"], "keywords": ["impression", "reçus", "tickets"]},
      {"id": "ventes-configuration-caisses", "title": "Configurer les caisses de vente", "objective": "Définir les comportements des caisses.", "location": "Ventes → Configuration → Caisses", "intro": "Paramètres caisse, comportements par défaut, association aux sessions et points de vente.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-caisses-gestion-caisses"], "keywords": ["configuration caisses", "sessions"]},
      {"id": "ventes-configuration-alertes", "title": "Configurer les alertes de ventes", "objective": "Définir les notifications et seuils commerciaux.", "location": "Ventes → Configuration → Alertes", "intro": "Seuils, alertes caisse, alertes factures, alertes performance et notifications.", "steps": ["Ouvrir la fonctionnalité concernée.", "Renseigner ou vérifier les informations utiles.", "Contrôler les impacts opérationnels.", "Valider puis suivre le résultat."], "callouts": [], "bestPractices": ["Contrôler les informations avant validation.", "Respecter les permissions et procédures internes."], "faq": ["Pourquoi l’action peut-elle être indisponible ?|Elle peut dépendre des permissions, de la configuration ou du statut de l’élément."], "related": ["ventes-dashboard-vue-ensemble"], "keywords": ["alertes", "seuils", "notifications"]}
    ].map(makeArticle),
    },
  ],
};
