
ALTER TABLE public.sessions_caisse
  ADD COLUMN IF NOT EXISTS total_ventes_global NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_bons NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS taux_marge NUMERIC(8,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valeur_marge NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS taux_marque NUMERIC(8,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valeur_marque NUMERIC(12,2) DEFAULT 0;
