// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzsoeapzuijhgemjzydo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6c29lYXB6dWlqaGdlbWp6eWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4Mzk4MzUsImV4cCI6MjA2NzQxNTgzNX0.GeDciO1Zxu4Q225D2nTisfd9O9SrPIvPuOtkWaQA8I0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});